// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {main} from '../models';
import {models} from '../models';
import {mcp} from '../models';

export function AddAgentTicketComment(arg1:string,arg2:string,arg3:boolean):Promise<json.RawMessage>;

export function AddTicketComment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddTicketCommentWithOptions(arg1:string,arg2:string,arg3:boolean):Promise<main.TicketComment>;

export function ClearChatHistory():Promise<void>;

export function ClearLogs():Promise<void>;

export function CloseAgentTicket(arg1:string,arg2:any,arg3:string,arg4:string):Promise<json.RawMessage>;

export function CloseSupportTicket(arg1:string,arg2:main.CloseTicketInput):Promise<main.APITicket>;

export function CreateAgentTicket(arg1:string,arg2:string,arg3:number,arg4:string):Promise<json.RawMessage>;

export function CreateSupportTicket(arg1:main.CreateTicketInput):Promise<main.APITicket>;

export function ExportInventoryMarkdown():Promise<string>;

export function ExportInventoryPDF():Promise<string>;

export function ExportMarkdown():Promise<string>;

export function ExportPDF():Promise<string>;

export function GetAgentInfo():Promise<main.AgentInfo>;

export function GetAgentInfoJSON():Promise<json.RawMessage>;

export function GetAgentStatus():Promise<main.AgentStatus>;

export function GetAgentTicketDetails(arg1:string):Promise<json.RawMessage>;

export function GetAvailableTools():Promise<Array<Record<string, string>>>;

export function GetCatalog():Promise<models.Catalog>;

export function GetChatConfig():Promise<main.ChatConfig>;

export function GetChatHistory():Promise<Array<main.ChatMessage>>;

export function GetDebugConfig():Promise<main.DebugConfig>;

export function GetInventory():Promise<models.InventoryReport>;

export function GetInventoryJSON():Promise<json.RawMessage>;

export function GetKnowledgeBaseArticles():Promise<Array<main.KnowledgeArticle>>;

export function GetLogs():Promise<Array<string>>;

export function GetLogsText():Promise<string>;

export function GetMCPRegistry():Promise<mcp.Registry>;

export function GetOsqueryStatus():Promise<models.OsqueryStatus>;

export function GetOsqueryStatusJSON():Promise<json.RawMessage>;

export function GetPendingUpdates():Promise<Array<models.UpgradeItem>>;

export function GetPendingUpdatesJSON():Promise<json.RawMessage>;

export function GetRealtimeStatus():Promise<main.RealtimeStatus>;

export function GetStartupError():Promise<string>;

export function GetSupportTicketDetails(arg1:string):Promise<main.APITicket>;

export function GetSupportTickets():Promise<Array<main.APITicket>>;

export function GetTicketComments(arg1:string):Promise<Array<main.TicketComment>>;

export function GetTicketWorkflowStates():Promise<Array<main.APIWorkflowState>>;

export function GetWatchdogHealth():Promise<Array<Record<string, any>>>;

export function Install(arg1:string):Promise<string>;

export function InstallOsquery():Promise<string>;

export function InstallPackage(arg1:string):Promise<string>;

export function ListAgentTickets():Promise<json.RawMessage>;

export function ListInstalled():Promise<string>;

export function RefreshInventory():Promise<models.InventoryReport>;

export function RequestAppClose():Promise<void>;

export function SearchCatalog(arg1:string):Promise<json.RawMessage>;

export function SearchKnowledgeBaseArticles(arg1:string):Promise<Array<main.KnowledgeArticle>>;

export function SendChatMessage(arg1:string):Promise<string>;

export function SetChatConfig(arg1:main.ChatConfig):Promise<void>;

export function SetDebugConfig(arg1:main.DebugConfig):Promise<void>;

export function SetExportRedaction(arg1:boolean):Promise<void>;

export function ShouldHideOnClose():Promise<boolean>;

export function StartChatStream(arg1:string):Promise<void>;

export function StopChatStream():Promise<boolean>;

export function TestChatConfig(arg1:main.ChatConfig):Promise<string>;

export function TestDebugConnection(arg1:main.DebugConfig):Promise<string>;

export function Uninstall(arg1:string):Promise<string>;

export function UninstallPackage(arg1:string):Promise<string>;

export function Upgrade(arg1:string):Promise<string>;

export function UpgradeAll():Promise<string>;

export function UpgradeAllPackages():Promise<string>;

export function UpgradePackage(arg1:string):Promise<string>;
