// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentTicketComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAgentTicketComment'](arg1, arg2, arg3);
}

export function AddTicketComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTicketComment'](arg1, arg2, arg3);
}

export function AddTicketCommentWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTicketCommentWithOptions'](arg1, arg2, arg3);
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CloseAgentTicket(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloseAgentTicket'](arg1, arg2, arg3, arg4);
}

export function CloseSupportTicket(arg1, arg2) {
  return window['go']['main']['App']['CloseSupportTicket'](arg1, arg2);
}

export function CreateAgentTicket(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAgentTicket'](arg1, arg2, arg3, arg4);
}

export function CreateSupportTicket(arg1) {
  return window['go']['main']['App']['CreateSupportTicket'](arg1);
}

export function ExportInventoryMarkdown() {
  return window['go']['main']['App']['ExportInventoryMarkdown']();
}

export function ExportInventoryPDF() {
  return window['go']['main']['App']['ExportInventoryPDF']();
}

export function ExportMarkdown() {
  return window['go']['main']['App']['ExportMarkdown']();
}

export function ExportPDF() {
  return window['go']['main']['App']['ExportPDF']();
}

export function GetAgentInfo() {
  return window['go']['main']['App']['GetAgentInfo']();
}

export function GetAgentInfoJSON() {
  return window['go']['main']['App']['GetAgentInfoJSON']();
}

export function GetAgentStatus() {
  return window['go']['main']['App']['GetAgentStatus']();
}

export function GetAgentTicketDetails(arg1) {
  return window['go']['main']['App']['GetAgentTicketDetails'](arg1);
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetChatConfig() {
  return window['go']['main']['App']['GetChatConfig']();
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetDebugConfig() {
  return window['go']['main']['App']['GetDebugConfig']();
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function GetInventoryJSON() {
  return window['go']['main']['App']['GetInventoryJSON']();
}

export function GetKnowledgeBaseArticles() {
  return window['go']['main']['App']['GetKnowledgeBaseArticles']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLogsText() {
  return window['go']['main']['App']['GetLogsText']();
}

export function GetMCPRegistry() {
  return window['go']['main']['App']['GetMCPRegistry']();
}

export function GetOsqueryStatus() {
  return window['go']['main']['App']['GetOsqueryStatus']();
}

export function GetOsqueryStatusJSON() {
  return window['go']['main']['App']['GetOsqueryStatusJSON']();
}

export function GetPendingUpdates() {
  return window['go']['main']['App']['GetPendingUpdates']();
}

export function GetPendingUpdatesJSON() {
  return window['go']['main']['App']['GetPendingUpdatesJSON']();
}

export function GetRealtimeStatus() {
  return window['go']['main']['App']['GetRealtimeStatus']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function GetSupportTicketDetails(arg1) {
  return window['go']['main']['App']['GetSupportTicketDetails'](arg1);
}

export function GetSupportTickets() {
  return window['go']['main']['App']['GetSupportTickets']();
}

export function GetTicketComments(arg1) {
  return window['go']['main']['App']['GetTicketComments'](arg1);
}

export function GetTicketWorkflowStates() {
  return window['go']['main']['App']['GetTicketWorkflowStates']();
}

export function GetWatchdogHealth() {
  return window['go']['main']['App']['GetWatchdogHealth']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function InstallOsquery() {
  return window['go']['main']['App']['InstallOsquery']();
}

export function InstallPackage(arg1) {
  return window['go']['main']['App']['InstallPackage'](arg1);
}

export function ListAgentTickets() {
  return window['go']['main']['App']['ListAgentTickets']();
}

export function ListInstalled() {
  return window['go']['main']['App']['ListInstalled']();
}

export function RefreshInventory() {
  return window['go']['main']['App']['RefreshInventory']();
}

export function RequestAppClose() {
  return window['go']['main']['App']['RequestAppClose']();
}

export function SearchCatalog(arg1) {
  return window['go']['main']['App']['SearchCatalog'](arg1);
}

export function SearchKnowledgeBaseArticles(arg1) {
  return window['go']['main']['App']['SearchKnowledgeBaseArticles'](arg1);
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}

export function SetChatConfig(arg1) {
  return window['go']['main']['App']['SetChatConfig'](arg1);
}

export function SetDebugConfig(arg1) {
  return window['go']['main']['App']['SetDebugConfig'](arg1);
}

export function SetExportRedaction(arg1) {
  return window['go']['main']['App']['SetExportRedaction'](arg1);
}

export function ShouldHideOnClose() {
  return window['go']['main']['App']['ShouldHideOnClose']();
}

export function StartChatStream(arg1) {
  return window['go']['main']['App']['StartChatStream'](arg1);
}

export function StopChatStream() {
  return window['go']['main']['App']['StopChatStream']();
}

export function TestChatConfig(arg1) {
  return window['go']['main']['App']['TestChatConfig'](arg1);
}

export function TestDebugConnection(arg1) {
  return window['go']['main']['App']['TestDebugConnection'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['main']['App']['UninstallPackage'](arg1);
}

export function Upgrade(arg1) {
  return window['go']['main']['App']['Upgrade'](arg1);
}

export function UpgradeAll() {
  return window['go']['main']['App']['UpgradeAll']();
}

export function UpgradeAllPackages() {
  return window['go']['main']['App']['UpgradeAllPackages']();
}

export function UpgradePackage(arg1) {
  return window['go']['main']['App']['UpgradePackage'](arg1);
}
