// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {database} from '../models';
import {main} from '../models';
import {models} from '../models';
import {mcp} from '../models';
import {context} from '../models';

export function AddAgentTicketComment(arg1:string,arg2:string,arg3:boolean):Promise<json.RawMessage>;

export function AddLocalMemory(arg1:string):Promise<database.MemoryNote>;

export function AddTicketComment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddTicketCommentWithOptions(arg1:string,arg2:string,arg3:boolean):Promise<main.TicketComment>;

export function CleanupP2PTempNow():Promise<string>;

export function ClearChatHistory():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearPrintQueue(arg1:string):Promise<json.RawMessage>;

export function ClearPrintQueueJSON(arg1:string):Promise<json.RawMessage>;

export function CloseAgentTicket(arg1:string,arg2:any,arg3:string,arg4:string):Promise<json.RawMessage>;

export function CloseSupportTicket(arg1:string,arg2:main.CloseTicketInput):Promise<main.APITicket>;

export function ComputeP2PSeedPlan(arg1:number):Promise<main.P2PSeedPlan>;

export function CreateAgentTicket(arg1:string,arg2:string,arg3:number,arg4:string):Promise<json.RawMessage>;

export function CreateSupportTicket(arg1:main.CreateTicketInput):Promise<main.APITicket>;

export function DeleteLocalMemory(arg1:number):Promise<void>;

export function DownloadP2PArtifactSwarm(arg1:string):Promise<main.P2PArtifactView>;

export function ExportInventoryMarkdown():Promise<string>;

export function ExportInventoryPDF():Promise<string>;

export function ExportMarkdown():Promise<string>;

export function ExportPDF():Promise<string>;

export function FindP2PArtifactPeers(arg1:string):Promise<main.P2PArtifactAvailabilityView>;

export function GetAgentConfiguration():Promise<main.AgentConfiguration>;

export function GetAgentInfo():Promise<main.AgentInfo>;

export function GetAgentInfoJSON():Promise<json.RawMessage>;

export function GetAgentStatus():Promise<main.AgentStatus>;

export function GetAgentTicketDetails(arg1:string):Promise<json.RawMessage>;

export function GetAutomationState():Promise<main.AutomationStateView>;

export function GetAvailableTools():Promise<Array<Record<string, string>>>;

export function GetCatalog():Promise<models.Catalog>;

export function GetChatConfig():Promise<main.ChatConfig>;

export function GetChatHistory():Promise<Array<main.ChatMessage>>;

export function GetDebugConfig():Promise<main.DebugConfig>;

export function GetInventory():Promise<models.InventoryReport>;

export function GetInventoryJSON():Promise<json.RawMessage>;

export function GetKnowledgeBaseArticles():Promise<Array<main.KnowledgeArticle>>;

export function GetLocalMemories():Promise<Array<database.MemoryNote>>;

export function GetLogs():Promise<Array<string>>;

export function GetLogsText():Promise<string>;

export function GetMCPRegistry():Promise<mcp.Registry>;

export function GetOsqueryStatus():Promise<models.OsqueryStatus>;

export function GetOsqueryStatusJSON():Promise<json.RawMessage>;

export function GetP2PArtifactAccess(arg1:string,arg2:string):Promise<main.P2PArtifactAccess>;

export function GetP2PConfig():Promise<main.P2PConfig>;

export function GetP2PDebugStatus():Promise<main.P2PDebugStatus>;

export function GetP2PDistributionStatus(arg1:context.Context):Promise<Array<main.P2PDistributionStatus>>;

export function GetP2PPeerArtifactIndex():Promise<Array<main.P2PPeerArtifactIndexView>>;

export function GetP2PPeers():Promise<Array<main.P2PPeerView>>;

export function GetP2PSeedPlanRecommendation(arg1:context.Context):Promise<main.P2PSeedPlanRecommendation>;

export function GetP2PTempDir():Promise<string>;

export function GetPackageActions():Promise<Record<string, string>>;

export function GetPackageActionsJSON():Promise<json.RawMessage>;

export function GetPendingUpdates():Promise<Array<models.UpgradeItem>>;

export function GetPendingUpdatesJSON():Promise<json.RawMessage>;

export function GetPrinterConfig(arg1:string):Promise<json.RawMessage>;

export function GetPrinterConfigJSON(arg1:string):Promise<json.RawMessage>;

export function GetRealtimeStatus():Promise<main.RealtimeStatus>;

export function GetRuntimeFlags():Promise<main.RuntimeFlags>;

export function GetSpoolerStatus():Promise<json.RawMessage>;

export function GetSpoolerStatusJSON():Promise<json.RawMessage>;

export function GetStartupError():Promise<string>;

export function GetStatusOverview():Promise<main.StatusOverview>;

export function GetSupportTicketDetails(arg1:string):Promise<main.APITicket>;

export function GetSupportTickets():Promise<Array<main.APITicket>>;

export function GetTicketComments(arg1:string):Promise<Array<main.TicketComment>>;

export function GetTicketWorkflowStates():Promise<Array<main.APIWorkflowState>>;

export function GetWatchdogHealth():Promise<Array<Record<string, any>>>;

export function Install(arg1:string):Promise<string>;

export function InstallOsquery():Promise<string>;

export function InstallPackage(arg1:string):Promise<string>;

export function InstallPrinter(arg1:string,arg2:string,arg3:string,arg4:string):Promise<json.RawMessage>;

export function InstallPrinterJSON(arg1:string,arg2:string,arg3:string,arg4:string):Promise<json.RawMessage>;

export function InstallSharedPrinter(arg1:string,arg2:boolean):Promise<json.RawMessage>;

export function InstallSharedPrinterJSON(arg1:string,arg2:boolean):Promise<json.RawMessage>;

export function IsTrayReady():Promise<boolean>;

export function ListAgentTickets():Promise<json.RawMessage>;

export function ListInstalled():Promise<string>;

export function ListP2PArtifacts():Promise<Array<main.P2PArtifactView>>;

export function ListP2PAuditEvents():Promise<Array<main.P2PAuditEvent>>;

export function ListP2PAuditEventsFiltered(arg1:string,arg2:string,arg3:string):Promise<Array<main.P2PAuditEvent>>;

export function ListPrintJobs(arg1:string):Promise<json.RawMessage>;

export function ListPrintJobsJSON(arg1:string):Promise<json.RawMessage>;

export function ListPrinterDrivers():Promise<json.RawMessage>;

export function ListPrinterDriversJSON():Promise<json.RawMessage>;

export function ListPrinters():Promise<json.RawMessage>;

export function ListPrintersJSON():Promise<json.RawMessage>;

export function PostP2PTelemetry(arg1:context.Context):Promise<void>;

export function PublishP2PTestArtifact(arg1:string,arg2:string):Promise<main.P2PArtifactView>;

export function PullP2PArtifactFromPeer(arg1:string,arg2:string):Promise<main.P2PArtifactView>;

export function RefreshAutomationPolicy(arg1:boolean):Promise<main.AutomationStateView>;

export function RefreshInventory():Promise<models.InventoryReport>;

export function RefreshP2PPeerCatalog():Promise<void>;

export function RemovePrintJob(arg1:string,arg2:number):Promise<json.RawMessage>;

export function RemovePrintJobJSON(arg1:string,arg2:number):Promise<json.RawMessage>;

export function RemovePrinter(arg1:string):Promise<json.RawMessage>;

export function RemovePrinterJSON(arg1:string):Promise<json.RawMessage>;

export function ReplicateP2PArtifactToPeer(arg1:string,arg2:string):Promise<string>;

export function RequestAppClose():Promise<void>;

export function RestartSpooler():Promise<json.RawMessage>;

export function RestartSpoolerJSON():Promise<json.RawMessage>;

export function RunOnboardingLoop(arg1:context.Context):Promise<void>;

export function SearchCatalog(arg1:string):Promise<json.RawMessage>;

export function SearchKnowledgeBaseArticles(arg1:string):Promise<Array<main.KnowledgeArticle>>;

export function SelectAndPublishP2PArtifact():Promise<main.P2PArtifactView>;

export function SendChatMessage(arg1:string):Promise<string>;

export function SetChatConfig(arg1:main.ChatConfig):Promise<void>;

export function SetDebugConfig(arg1:main.DebugConfig):Promise<void>;

export function SetExportRedaction(arg1:boolean):Promise<void>;

export function SetP2PConfig(arg1:main.P2PConfig):Promise<void>;

export function ShouldHideOnClose():Promise<boolean>;

export function StartChatStream(arg1:string):Promise<void>;

export function StartP2PTelemetryLoop(arg1:context.Context):Promise<void>;

export function StopChatStream():Promise<boolean>;

export function TestChatConfig(arg1:main.ChatConfig):Promise<string>;

export function TestDebugConnection(arg1:main.DebugConfig):Promise<string>;

export function Uninstall(arg1:string):Promise<string>;

export function UninstallPackage(arg1:string):Promise<string>;

export function Upgrade(arg1:string):Promise<string>;

export function UpgradeAll():Promise<string>;

export function UpgradeAllPackages():Promise<string>;

export function UpgradePackage(arg1:string):Promise<string>;
