// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * Overview provides a simplified health snapshot for the default status page.
 */
export class Overview {
    /**
     * Creates a new Overview instance.
     * @param {Partial<Overview>} [$$source = {}] - The source object to create the Overview.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("transportConnected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["transportConnected"] = false;
        }
        if (!("connectionLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectionLabel"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["onlineReason"] = undefined;
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("connectionType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectionType"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastGlobalPongAtUtc"] = undefined;
        }
        if (!("globalPongStale" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["globalPongStale"] = false;
        }
        if (!("nonCriticalDeferred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nonCriticalDeferred"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nonCriticalDeferredUntilUtc"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nonCriticalDeferredReason"] = undefined;
        }
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["appCommit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["buildDateUtc"] = undefined;
        }
        if (!("osName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osName"] = "";
        }
        if (!("osVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osVersion"] = "";
        }
        if (!("lastInventoryCollected" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastInventoryCollected"] = "";
        }
        if (!("realtimeAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["realtimeAvailable"] = false;
        }
        if (!("realtimeNatsConnected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["realtimeNatsConnected"] = false;
        }
        if (!("realtimeConnectedAgents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["realtimeConnectedAgents"] = 0;
        }
        if (!("realtimeMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["realtimeMessage"] = "";
        }
        if (!("checkedAtUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAtUtc"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("pendingCommandResults" in $$source)) {
            /**
             * Outbox offline queue backlog counts
             * @member
             * @type {number}
             */
            this["pendingCommandResults"] = 0;
        }
        if (!("pendingP2pTelemetry" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingP2pTelemetry"] = 0;
        }
        if (!("updateCheckEnabled" in $$source)) {
            /**
             * Update do agente (self-update)
             * @member
             * @type {boolean}
             */
            this["updateCheckEnabled"] = false;
        }
        if (!("updateCheckInProgress" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateCheckInProgress"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastUpdateCheckAtUtc"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updateLastError"] = undefined;
        }
        if (!("updateLastInstallerExitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updateLastInstallerExitCode"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updatePendingTargetVersion"] = undefined;
        }
        if (!("updateDownloadOkCount" in $$source)) {
            /**
             * Contadores de telemetria do self-update
             * @member
             * @type {number}
             */
            this["updateDownloadOkCount"] = 0;
        }
        if (!("updateLaunchOkCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updateLaunchOkCount"] = 0;
        }
        if (!("updateLaunchFailCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updateLaunchFailCount"] = 0;
        }
        if (!("updateInstallCompleteCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updateInstallCompleteCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Overview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Overview(/** @type {Partial<Overview>} */($$parsedSource));
    }
}
