// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as automation$0 from "./automation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as debug$0 from "./debug/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as p2pmeta$0 from "./p2pmeta/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as supportmeta$0 from "./supportmeta/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../internal/database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../internal/mcp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../encoding/json/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} ticketID
 * @param {string} content
 * @param {boolean} isInternal
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function AddAgentTicketComment(ticketID, content, isInternal) {
    return $Call.ByID(2286313891, ticketID, content, isInternal);
}

/**
 * AddLocalMemory cria uma nova anotacao local.
 * @param {string} content
 * @returns {$CancellablePromise<database$0.MemoryNote>}
 */
export function AddLocalMemory(content) {
    return $Call.ByID(2130441879, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddMyTicketComment adiciona um comentário ao ticket.
 * @param {string} ticketID
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function AddMyTicketComment(ticketID, content) {
    return $Call.ByID(814921856, ticketID, content);
}

/**
 * @param {string} ticketID
 * @param {string} author
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function AddTicketComment(ticketID, author, content) {
    return $Call.ByID(3132850490, ticketID, author, content);
}

/**
 * @param {string} ticketID
 * @param {string} content
 * @param {boolean} isInternal
 * @returns {$CancellablePromise<$models.TicketComment>}
 */
export function AddTicketCommentWithOptions(ticketID, content, isInternal) {
    return $Call.ByID(2500863336, ticketID, content, isInternal).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AnswerChatQuestion is the Wails binding called by the frontend when the user clicks an option.
 * @param {string} questionID
 * @param {string} answer
 * @returns {$CancellablePromise<void>}
 */
export function AnswerChatQuestion(questionID, answer) {
    return $Call.ByID(394857938, questionID, answer);
}

/**
 * AskUser displays a question to the user and waits for their answer.
 * This blocks the calling goroutine until the user responds or timeout is reached.
 * @param {string} question
 * @param {string} optionsJSON
 * @param {string} allowTextRaw
 * @returns {$CancellablePromise<string>}
 */
export function AskUser(question, optionsJSON, allowTextRaw) {
    return $Call.ByID(2699783508, question, optionsJSON, allowTextRaw);
}

/**
 * AskUserChat exibe uma pergunta interativa ao usuário e aguarda a resposta.
 * Implementa AppBridge.AskUserChat para o MCP tool ask_user.
 * @param {string} question
 * @param {string} optionsJSON
 * @param {string} allowText
 * @returns {$CancellablePromise<string>}
 */
export function AskUserChat(question, optionsJSON, allowText) {
    return $Call.ByID(2424954738, question, optionsJSON, allowText);
}

/**
 * CheckAgentUpdate dispara uma verificação manual de atualização do agente.
 * Aciona o mesmo fluxo do check automático de startup (respeita a política de
 * update), mas sem esperar pelo timer interno.
 * @returns {$CancellablePromise<void>}
 */
export function CheckAgentUpdate() {
    return $Call.ByID(1768401262);
}

/**
 * @returns {$CancellablePromise<$models.PSADTModuleStatus>}
 */
export function CheckPSADTModuleStatus() {
    return $Call.ByID(3062415680).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function CleanupP2PTempNow() {
    return $Call.ByID(3716382082);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ClearAllP2PArtifacts() {
    return $Call.ByID(627630723);
}

/**
 * ClearChatHistory resets the conversation.
 * @returns {$CancellablePromise<void>}
 */
export function ClearChatHistory() {
    return $Call.ByID(1059077319);
}

/**
 * ClearLogs empties the log buffer.
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(3954505520);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearMemoryCaches() {
    return $Call.ByID(3144519871);
}

/**
 * @param {string} printerName
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ClearPrintQueue(printerName) {
    return $Call.ByID(2274364485, printerName);
}

/**
 * @param {string} printerName
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ClearPrintQueueJSON(printerName) {
    return $Call.ByID(3013170755, printerName);
}

/**
 * @param {string} ticketID
 * @param {number | null} rating
 * @param {string} comment
 * @param {string} workflowStateID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function CloseAgentTicket(ticketID, rating, comment, workflowStateID) {
    return $Call.ByID(4198364011, ticketID, rating, comment, workflowStateID);
}

/**
 * CloseMyTicket fecha e avalia um ticket.
 * @param {string} ticketID
 * @param {number} rating
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function CloseMyTicket(ticketID, rating, notes) {
    return $Call.ByID(1146506252, ticketID, rating, notes);
}

/**
 * @param {string} ticketID
 * @param {$models.CloseTicketInput} input
 * @returns {$CancellablePromise<$models.APITicket>}
 */
export function CloseSupportTicket(ticketID, input) {
    return $Call.ByID(549080437, ticketID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {number} totalAgents
 * @returns {$CancellablePromise<$models.P2PSeedPlan>}
 */
export function ComputeP2PSeedPlan(totalAgents) {
    return $Call.ByID(2632336337, totalAgents).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} title
 * @param {string} description
 * @param {number} priority
 * @param {string} category
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function CreateAgentTicket(title, description, priority, category) {
    return $Call.ByID(124489267, title, description, priority, category);
}

/**
 * CreateMyTicket cria um novo ticket.
 * @param {$models.CreateTicketRequest} reqBody
 * @returns {$CancellablePromise<$models.TicketSummary | null>}
 */
export function CreateMyTicket(reqBody) {
    return $Call.ByID(647068532, reqBody).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.CreateTicketInput} input
 * @returns {$CancellablePromise<$models.APITicket>}
 */
export function CreateSupportTicket(input) {
    return $Call.ByID(2989565021, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Ctx() {
    return $Call.ByID(3912995967);
}

/**
 * DeleteLocalMemory remove uma nota pelo seu ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLocalMemory(id) {
    return $Call.ByID(297912715, id);
}

/**
 * DeleteP2PArtifact remove um único artifact (arquivo + manifest + cache SHA256) do diretório P2P.
 * @param {string} artifactName
 * @returns {$CancellablePromise<string>}
 */
export function DeleteP2PArtifact(artifactName) {
    return $Call.ByID(959338803, artifactName);
}

/**
 * DetectApiFeatures testa a conectividade com a API e detecta quais features estão disponíveis.
 * Faz um GET para /me/configuration e testa endpoints opcionais.
 * @returns {$CancellablePromise<$models.ApiVersionInfo | null>}
 */
export function DetectApiFeatures() {
    return $Call.ByID(2366186640).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {$models.NotificationDispatchRequest} req
 * @returns {$CancellablePromise<$models.NotificationDispatchResponse>}
 */
export function DispatchNotification(req) {
    return $Call.ByID(2878630075, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * DownloadP2PArtifactSwarm finds all peers that have the artifact and performs
 * a chunked swarm download when ≥2 peers are available; otherwise falls back
 * to the single-peer path.
 * @param {string} artifactName
 * @returns {$CancellablePromise<$models.P2PArtifactView>}
 */
export function DownloadP2PArtifactSwarm(artifactName) {
    return $Call.ByID(3531730818, artifactName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {$models.PSADTDebugNotificationRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function EmitPSADTDebugNotification(req) {
    return $Call.ByID(3418494989, req);
}

/**
 * ExecuteCustomPSADTScript executa um script PSADT customizado fornecido pelo usuário
 * @param {string} scriptContent
 * @returns {$CancellablePromise<$models.PSADTScriptResult>}
 */
export function ExecuteCustomPSADTScript(scriptContent) {
    return $Call.ByID(540611217, scriptContent).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ExecutePSADTTestScript executa um script PSADT de teste usando o módulo real
 * @param {string} appName
 * @param {string} appVersion
 * @returns {$CancellablePromise<$models.PSADTScriptResult>}
 */
export function ExecutePSADTTestScript(appName, appVersion) {
    return $Call.ByID(1972049288, appName, appVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ExecutePSADTVisualNotification executa uma notificacao visual nativa via cmdlets reais do PSAppDeployToolkit.
 * Grava um .ps1 temporario, executa com PowerShell -File e remove o arquivo ao terminar.
 * @param {$models.PSADTVisualNotificationRequest} req
 * @returns {$CancellablePromise<$models.PSADTScriptResult>}
 */
export function ExecutePSADTVisualNotification(req) {
    return $Call.ByID(3179337240, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ExportInventoryMarkdown exports inventory data in Markdown format.
 * @returns {$CancellablePromise<string>}
 */
export function ExportInventoryMarkdown() {
    return $Call.ByID(4161481573);
}

/**
 * ExportInventoryPDF exports inventory data in PDF format.
 * @returns {$CancellablePromise<string>}
 */
export function ExportInventoryPDF() {
    return $Call.ByID(3589786994);
}

/**
 * ExportLogs returns log content formatted for file export, optionally filtered.
 * @param {string} filterOrigin
 * @returns {$CancellablePromise<string>}
 */
export function ExportLogs(filterOrigin) {
    return $Call.ByID(274895867, filterOrigin);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportMarkdown() {
    return $Call.ByID(1307081673);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportPDF() {
    return $Call.ByID(349093206);
}

/**
 * FindP2PArtifactPeers returns availability of an artifact across known peers.
 * Lookup is performed exclusively by canonical ArtifactID.
 * @param {string} artifactName
 * @returns {$CancellablePromise<$models.P2PArtifactAvailabilityView>}
 */
export function FindP2PArtifactPeers(artifactName) {
    return $Call.ByID(1714534520, artifactName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AgentConfiguration>}
 */
export function GetAgentConfiguration() {
    return $Call.ByID(1761911899).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AgentInfo>}
 */
export function GetAgentInfo() {
    return $Call.ByID(2162875159).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetAgentInfoJSON() {
    return $Call.ByID(2128964709);
}

/**
 * @returns {$CancellablePromise<$models.AgentStatus>}
 */
export function GetAgentStatus() {
    return $Call.ByID(42559989).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} ticketID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetAgentTicketDetails(ticketID) {
    return $Call.ByID(1896456315, ticketID);
}

/**
 * GetAutoProvisioningStats retorna estatísticas de auto-provisioning do lado
 * deste agente enquanto provisionador (agente configurado que entrega ofertas).
 * Útil para monitorar quantos agentes genéricos este peer já configurou.
 * @returns {$CancellablePromise<$models.P2PAutoProvisioningStats>}
 */
export function GetAutoProvisioningStats() {
    return $Call.ByID(1243203927).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AutomationStateView>}
 */
export function GetAutomationState() {
    return $Call.ByID(2021899546).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetAvailableTools returns the list of MCP tools for display.
 * @returns {$CancellablePromise<{ [_ in string]?: string }[]>}
 */
export function GetAvailableTools() {
    return $Call.ByID(2472798884).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Catalog>}
 */
export function GetCatalog() {
    return $Call.ByID(2156134909).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetChatConfig returns the current config (API key masked).
 * @returns {$CancellablePromise<$models.ChatConfig>}
 */
export function GetChatConfig() {
    return $Call.ByID(2978849638).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetChatHistory returns the conversation for display.
 * @returns {$CancellablePromise<$models.ChatMessage[]>}
 */
export function GetChatHistory() {
    return $Call.ByID(1722802992).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DebugConfig>}
 */
export function GetDebugConfig() {
    return $Call.ByID(2473342835).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetDebugHTTPPort returns the port the debug HTTP server is listening on, or 0 if not running.
 * @returns {$CancellablePromise<number>}
 */
export function GetDebugHTTPPort() {
    return $Call.ByID(2074510754);
}

/**
 * GetHardwareIdentity retorna as identidades de hardware da máquina (TPM EK e
 * UUID SMBIOS). É exposto ao frontend via Wails e ao debug HTTP via /api/.
 * 
 * O resultado é cacheado no App: o hardware não muda em runtime, e a coleta
 * (TPM + WMI) é relativamente lenta. A primeira chamada coleta e cacheia; as
 * chamadas seguintes retornam do cache imediatamente.
 * @returns {$CancellablePromise<$models.HardwareIdentityInfo>}
 */
export function GetHardwareIdentity() {
    return $Call.ByID(939318840).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.InventoryReport>}
 */
export function GetInventory() {
    return $Call.ByID(3541590274).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetInventoryJSON() {
    return $Call.ByID(4178393244);
}

/**
 * @param {string} articleID
 * @returns {$CancellablePromise<$models.KnowledgeArticle>}
 */
export function GetKnowledgeArticleDetails(articleID) {
    return $Call.ByID(277603790, articleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {string} category
 * @returns {$CancellablePromise<$models.KnowledgeArticle[]>}
 */
export function GetKnowledgeArticles(category) {
    return $Call.ByID(2070621185, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.KnowledgeArticle[]>}
 */
export function GetKnowledgeBaseArticles() {
    return $Call.ByID(4222193444).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * GetLocalMemories retorna as memorias/anotacoes locais persistidas.
 * Esta API é exposta via Wails e MCP.
 * @returns {$CancellablePromise<database$0.MemoryNote[]>}
 */
export function GetLocalMemories() {
    return $Call.ByID(1215318446).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetLogCount returns the total number of buffered log lines.
 * @returns {$CancellablePromise<number>}
 */
export function GetLogCount() {
    return $Call.ByID(3906542691);
}

/**
 * GetLogs returns the accumulated command log lines.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogs() {
    return $Call.ByID(3090090525).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLogsText() {
    return $Call.ByID(2254800806);
}

/**
 * GetMCPRegistry returns the registry (used by main.go for MCP server mode).
 * @returns {$CancellablePromise<mcp$0.Registry | null>}
 */
export function GetMCPRegistry() {
    return $Call.ByID(4204585049).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetMyTickets lista tickets do agente.
 * @param {string} workflowStateID
 * @returns {$CancellablePromise<$models.TicketSummary[]>}
 */
export function GetMyTickets(workflowStateID) {
    return $Call.ByID(616944413, workflowStateID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * GetOnboardingStatus retorna o status do agente sob perspectiva de onboarding:
 * se está configurado ou aguardando provisionamento automático da rede P2P.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetOnboardingStatus() {
    return $Call.ByID(435522917).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.OsqueryStatus>}
 */
export function GetOsqueryStatus() {
    return $Call.ByID(3443049766).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetOsqueryStatusJSON() {
    return $Call.ByID(2619613312);
}

/**
 * @param {string} artifactName
 * @param {string} targetPeerID
 * @returns {$CancellablePromise<$models.P2PArtifactAccess>}
 */
export function GetP2PArtifactAccess(artifactName, targetPeerID) {
    return $Call.ByID(1582468356, artifactName, targetPeerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.P2PConfig>}
 */
export function GetP2PConfig() {
    return $Call.ByID(2853747614).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.P2PDebugStatus>}
 */
export function GetP2PDebugStatus() {
    return $Call.ByID(386736961).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * GetP2PDistributionStatus fetches distribution visibility used by operations dashboards.
 * @returns {$CancellablePromise<$models.P2PDistributionStatus[]>}
 */
export function GetP2PDistributionStatus() {
    return $Call.ByID(2586216540).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * GetP2PDistributionStatusWithOptions fetches distribution visibility using
 * optional filters and pagination.
 * @param {$models.P2PDistributionStatusQueryOptions} opts
 * @returns {$CancellablePromise<$models.P2PDistributionStatus[]>}
 */
export function GetP2PDistributionStatusWithOptions(opts) {
    return $Call.ByID(3990011018, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.P2PPeerArtifactIndexView[]>}
 */
export function GetP2PPeerArtifactIndex() {
    return $Call.ByID(1978502146).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.P2PPeerView[]>}
 */
export function GetP2PPeers() {
    return $Call.ByID(3590775973).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * GetP2PSeedPlanRecommendation returns a cached plan when fresh, otherwise
 * fetches from API and updates local cache.
 * @returns {$CancellablePromise<$models.P2PSeedPlanRecommendation>}
 */
export function GetP2PSeedPlanRecommendation() {
    return $Call.ByID(508162245).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetP2PTempDir() {
    return $Call.ByID(2760207741);
}

/**
 * @returns {$CancellablePromise<$models.PSADTDebugState>}
 */
export function GetPSADTDebugState() {
    return $Call.ByID(2789250514).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * GetPSADTScriptTemplate retorna um template de script PSADT para customização
 * @returns {$CancellablePromise<string>}
 */
export function GetPSADTScriptTemplate() {
    return $Call.ByID(929390123);
}

/**
 * GetPackageActions returns a contextual action map keyed by package id.
 * Values: install, uninstall, upgrade.
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetPackageActions() {
    return $Call.ByID(3765516573).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetPackageActionsJSON() {
    return $Call.ByID(3386962891);
}

/**
 * GetPendingUpdates runs `winget upgrade` and parses the output into structured items.
 * @returns {$CancellablePromise<models$0.UpgradeItem[]>}
 */
export function GetPendingUpdates() {
    return $Call.ByID(514441265).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetPendingUpdatesJSON() {
    return $Call.ByID(1731196975);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetPreferredLocale() {
    return $Call.ByID(216923105);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetPrinterConfig(name) {
    return $Call.ByID(4174023268, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetPrinterConfigJSON(name) {
    return $Call.ByID(532792342, name);
}

/**
 * @returns {$CancellablePromise<$models.RealtimeStatus>}
 */
export function GetRealtimeStatus() {
    return $Call.ByID(2038236921).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RuntimeFlags>}
 */
export function GetRuntimeFlags() {
    return $Call.ByID(2140353209).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetServiceHealth() {
    return $Call.ByID(1809179847).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetSpoolerStatus() {
    return $Call.ByID(2534156520);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetSpoolerStatusJSON() {
    return $Call.ByID(2652150090);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetStartupError() {
    return $Call.ByID(207231763);
}

/**
 * GetStatusOverview returns a user-friendly status summary for the Status tab.
 * @returns {$CancellablePromise<$models.StatusOverview>}
 */
export function GetStatusOverview() {
    return $Call.ByID(4003627099).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * @param {string} ticketID
 * @returns {$CancellablePromise<$models.APITicket>}
 */
export function GetSupportTicketDetails(ticketID) {
    return $Call.ByID(1851658405, ticketID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.APITicket[]>}
 */
export function GetSupportTickets() {
    return $Call.ByID(2418825250).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * @param {string} ticketID
 * @returns {$CancellablePromise<$models.TicketComment[]>}
 */
export function GetTicketComments(ticketID) {
    return $Call.ByID(3718392116, ticketID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.APIWorkflowState[]>}
 */
export function GetTicketWorkflowStates() {
    return $Call.ByID(2054776725).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function Install(id) {
    return $Call.ByID(2932162137, id);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function InstallOsquery() {
    return $Call.ByID(3817496113);
}

/**
 * @param {string} version
 * @returns {$CancellablePromise<$models.PSADTModuleStatus>}
 */
export function InstallPSADTModule(version) {
    return $Call.ByID(124056039, version).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function InstallPackage(id) {
    return $Call.ByID(28384887, id);
}

/**
 * @param {string} name
 * @param {string} driverName
 * @param {string} portName
 * @param {string} portAddress
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function InstallPrinter(name, driverName, portName, portAddress) {
    return $Call.ByID(3706912291, name, driverName, portName, portAddress);
}

/**
 * @param {string} name
 * @param {string} driverName
 * @param {string} portName
 * @param {string} portAddress
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function InstallPrinterJSON(name, driverName, portName, portAddress) {
    return $Call.ByID(439639441, name, driverName, portName, portAddress);
}

/**
 * @param {string} connectionPath
 * @param {boolean} setDefault
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function InstallSharedPrinter(connectionPath, setDefault) {
    return $Call.ByID(3514921780, connectionPath, setDefault);
}

/**
 * @param {string} connectionPath
 * @param {boolean} setDefault
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function InstallSharedPrinterJSON(connectionPath, setDefault) {
    return $Call.ByID(1144700806, connectionPath, setDefault);
}

/**
 * IsDebugHTTPBoundToAllInterfaces returns whether the debug HTTP server is bound
 * to 0.0.0.0 (all network interfaces) instead of the default 127.0.0.1.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDebugHTTPBoundToAllInterfaces() {
    return $Call.ByID(2915212725);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsTrayReady() {
    return $Call.ByID(339088425);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListAgentTickets() {
    return $Call.ByID(2566506872);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ListInstalled() {
    return $Call.ByID(2984852148);
}

/**
 * @returns {$CancellablePromise<$models.P2PArtifactView[]>}
 */
export function ListP2PArtifacts() {
    return $Call.ByID(1832312099).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType56($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.P2PAuditEvent[]>}
 */
export function ListP2PAuditEvents() {
    return $Call.ByID(2100415322).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType58($result);
    }));
}

/**
 * @param {string} action
 * @param {string} peerAgentID
 * @param {string} status
 * @returns {$CancellablePromise<$models.P2PAuditEvent[]>}
 */
export function ListP2PAuditEventsFiltered(action, peerAgentID, status) {
    return $Call.ByID(1530405413, action, peerAgentID, status).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType58($result);
    }));
}

/**
 * @param {string} printerName
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListPrintJobs(printerName) {
    return $Call.ByID(2577288561, printerName);
}

/**
 * @param {string} printerName
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListPrintJobsJSON(printerName) {
    return $Call.ByID(4277360239, printerName);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListPrinterDrivers() {
    return $Call.ByID(3683646533);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListPrinterDriversJSON() {
    return $Call.ByID(2208843331);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListPrinters() {
    return $Call.ByID(1506384155);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListPrintersJSON() {
    return $Call.ByID(401928665);
}

/**
 * PostP2PTelemetry sends runtime P2P metrics to server for observability.
 * @returns {$CancellablePromise<void>}
 */
export function PostP2PTelemetry() {
    return $Call.ByID(3626139357);
}

/**
 * PublishChatEvent publica um evento de chat para os inscritos SSE.
 * Chamado por StartChatStream para forward dos eventos Wails → HTTP.
 * @param {string} eventType
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function PublishChatEvent(eventType, data) {
    return $Call.ByID(2636342125, eventType, data);
}

/**
 * @param {string} artifactName
 * @param {string} content
 * @returns {$CancellablePromise<$models.P2PArtifactView>}
 */
export function PublishP2PTestArtifact(artifactName, content) {
    return $Call.ByID(2051842247, artifactName, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} artifactName
 * @param {string} sourcePeerID
 * @returns {$CancellablePromise<$models.P2PArtifactView>}
 */
export function PullP2PArtifactFromPeer(artifactName, sourcePeerID) {
    return $Call.ByID(2320787459, artifactName, sourcePeerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {boolean} includeScriptContent
 * @returns {$CancellablePromise<$models.AutomationStateView>}
 */
export function RefreshAutomationPolicy(includeScriptContent) {
    return $Call.ByID(2602153952, includeScriptContent).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * RefreshHardwareIdentity limpa o cache e re-coleta a identidade de hardware.
 * Útil quando o usuário quer forçar uma nova leitura (ex.: após habilitar o TPM
 * na BIOS). Exposto ao frontend via Wails e ao debug HTTP via /api/.
 * @returns {$CancellablePromise<$models.HardwareIdentityInfo>}
 */
export function RefreshHardwareIdentity() {
    return $Call.ByID(2891408067).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.InventoryReport>}
 */
export function RefreshInventory() {
    return $Call.ByID(2772913491).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * RefreshKnowledgeBase limpa o cache local e recarrega os artigos da API.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshKnowledgeBase() {
    return $Call.ByID(2357832466);
}

/**
 * @returns {$CancellablePromise<models$0.ListeningPortInfo[]>}
 */
export function RefreshListeningPorts() {
    return $Call.ByID(1221992142).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType60($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.NetworkConnectionsReport>}
 */
export function RefreshNetworkConnections() {
    return $Call.ByID(964299066).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType61($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RefreshP2PPeerCatalog() {
    return $Call.ByID(3000278848);
}

/**
 * @returns {$CancellablePromise<models$0.SoftwareItem[]>}
 */
export function RefreshSoftware() {
    return $Call.ByID(2717679924).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.StartupItem[]>}
 */
export function RefreshStartupItems() {
    return $Call.ByID(3800784882).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * RegisterAgentToolsOnServer envia a lista de tools MCP para a API.
 * @returns {$CancellablePromise<void>}
 */
export function RegisterAgentToolsOnServer() {
    return $Call.ByID(2784273297);
}

/**
 * @param {string} printerName
 * @param {number} jobID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RemovePrintJob(printerName, jobID) {
    return $Call.ByID(2938190880, printerName, jobID);
}

/**
 * @param {string} printerName
 * @param {number} jobID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RemovePrintJobJSON(printerName, jobID) {
    return $Call.ByID(1303420946, printerName, jobID);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RemovePrinter(name) {
    return $Call.ByID(190803298, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RemovePrinterJSON(name) {
    return $Call.ByID(3178073468, name);
}

/**
 * @param {string} artifactName
 * @param {string} targetPeerID
 * @returns {$CancellablePromise<string>}
 */
export function ReplicateP2PArtifactToPeer(artifactName, targetPeerID) {
    return $Call.ByID(1152031174, artifactName, targetPeerID);
}

/**
 * ReportUIRuntimeState is a no-op (watchdog system removed).
 * @param {boolean} visible
 * @param {boolean} focused
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function ReportUIRuntimeState(visible, focused, source) {
    return $Call.ByID(1278733855, visible, focused, source);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RequestAppClose() {
    return $Call.ByID(4204399758);
}

/**
 * @param {string} notificationID
 * @param {string} result
 * @returns {$CancellablePromise<boolean>}
 */
export function RespondToNotification(notificationID, result) {
    return $Call.ByID(930300781, notificationID, result);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RestartSpooler() {
    return $Call.ByID(16122767);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RestartSpoolerJSON() {
    return $Call.ByID(945611693);
}

/**
 * RunOnboardingLoop periodically requests configuration from the local P2P network
 * when this agent has no server credentials ("generic agent" state).
 * Exits when configured, max attempts reached, or ctx cancelled.
 * @returns {$CancellablePromise<void>}
 */
export function RunOnboardingLoop() {
    return $Call.ByID(3935230048);
}

/**
 * RunPSADTPreflightChecks executa verificacoes pre-flight usando a lib go-psadt.
 * @returns {$CancellablePromise<$models.PSADTPreflightResult>}
 */
export function RunPSADTPreflightChecks() {
    return $Call.ByID(2615823421).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType66($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function SearchCatalog(query) {
    return $Call.ByID(4137195361, query);
}

/**
 * @returns {$CancellablePromise<$models.P2PArtifactView>}
 */
export function SelectAndPublishP2PArtifact() {
    return $Call.ByID(1369003166).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * SendChatMessage sends a user message and returns the assistant response.
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function SendChatMessage(message) {
    return $Call.ByID(2406688925, message);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SendTestHeartbeat() {
    return $Call.ByID(2300911828);
}

/**
 * SetChatConfig updates and persists the LLM API settings.
 * @param {$models.ChatConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetChatConfig(cfg) {
    return $Call.ByID(2758197282, cfg);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(3742246789);
}

/**
 * @param {$models.DebugConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetDebugConfig(cfg) {
    return $Call.ByID(1390084319, cfg);
}

/**
 * SetDebugHTTPBindAllInterfaces restarts the debug HTTP server to bind on
 * 0.0.0.0 (when enabled=true) or 127.0.0.1 (when enabled=false).
 * Preserves the current port so tray menu "Abrir no navegador" and other
 * references remain valid after the rebind.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDebugHTTPBindAllInterfaces(enabled) {
    return $Call.ByID(3344035097, enabled);
}

/**
 * SetExportRedaction toggles redaction for export.
 * @param {boolean} redact
 * @returns {$CancellablePromise<void>}
 */
export function SetExportRedaction(redact) {
    return $Call.ByID(2638712837, redact);
}

/**
 * @param {$models.P2PConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetP2PConfig(cfg) {
    return $Call.ByID(327634346, cfg);
}

/**
 * SetUIRuntimeSuspended is a no-op (watchdog system removed).
 * @param {boolean} suspended
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function SetUIRuntimeSuspended(suspended, reason) {
    return $Call.ByID(1498770781, suspended, reason);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ShouldHideOnClose() {
    return $Call.ByID(2081071652);
}

/**
 * StartChatStream sends a chat message and streams the response via Wails events.
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function StartChatStream(message) {
    return $Call.ByID(2817758308, message);
}

/**
 * StartDebugHTTPServer binds a local-only HTTP server on a random port.
 * The server serves static frontend assets and a /api/* REST bridge.
 * @returns {$CancellablePromise<void>}
 */
export function StartDebugHTTPServer() {
    return $Call.ByID(3899334034);
}

/**
 * StartP2PTelemetryLoop periodically refreshes seed-plan cache and sends telemetry.
 * @returns {$CancellablePromise<void>}
 */
export function StartP2PTelemetryLoop() {
    return $Call.ByID(2627777121);
}

/**
 * StopChatStream interrupts the active streamed AI response, if running.
 * @returns {$CancellablePromise<boolean>}
 */
export function StopChatStream() {
    return $Call.ByID(1128091748);
}

/**
 * StopDebugHTTPServer gracefully shuts down the debug HTTP server.
 * @returns {$CancellablePromise<void>}
 */
export function StopDebugHTTPServer() {
    return $Call.ByID(1220104594);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SyncNetworkConnections() {
    return $Call.ByID(441645050);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SyncP2PBootstrapNow() {
    return $Call.ByID(3361015351);
}

/**
 * TestChatConfig checks whether the informed LLM settings are valid without saving them.
 * @param {$models.ChatConfig} cfg
 * @returns {$CancellablePromise<string>}
 */
export function TestChatConfig(cfg) {
    return $Call.ByID(1365491746, cfg);
}

/**
 * @param {$models.DebugConfig} cfg
 * @returns {$CancellablePromise<string>}
 */
export function TestDebugConnection(cfg) {
    return $Call.ByID(3264904545, cfg);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function Uninstall(id) {
    return $Call.ByID(2191669964, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function UninstallPackage(id) {
    return $Call.ByID(3174179940, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function Upgrade(id) {
    return $Call.ByID(2236392866, id);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function UpgradeAll() {
    return $Call.ByID(3842666937);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function UpgradeAllPackages() {
    return $Call.ByID(1632584044);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function UpgradePackage(id) {
    return $Call.ByID(2573219610, id);
}

/**
 * UpsertCollectedCustomField envia um campo customizado coletado para o servidor.
 * @param {string} name
 * @param {string} value
 * @param {string} scope
 * @returns {$CancellablePromise<void>}
 */
export function UpsertCollectedCustomField(name, value, scope) {
    return $Call.ByID(1003085221, name, value, scope);
}

// Private type creation functions
const $$createType0 = database$0.MemoryNote.createFrom;
const $$createType1 = supportmeta$0.TicketComment.createFrom;
const $$createType2 = $models.PSADTModuleStatus.createFrom;
const $$createType3 = supportmeta$0.APITicket.createFrom;
const $$createType4 = p2pmeta$0.SeedPlan.createFrom;
const $$createType5 = $models.TicketSummary.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.ApiVersionInfo.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.NotificationDispatchResponse.createFrom;
const $$createType10 = p2pmeta$0.ArtifactView.createFrom;
const $$createType11 = $models.PSADTScriptResult.createFrom;
const $$createType12 = p2pmeta$0.ArtifactAvailabilityView.createFrom;
const $$createType13 = $models.AgentConfiguration.createFrom;
const $$createType14 = supportmeta$0.AgentInfo.createFrom;
const $$createType15 = debug$0.AgentStatus.createFrom;
const $$createType16 = p2pmeta$0.AutoProvisioningStats.createFrom;
const $$createType17 = automation$0.StateView.createFrom;
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = models$0.Catalog.createFrom;
const $$createType21 = $models.ChatConfig.createFrom;
const $$createType22 = $models.ChatMessage.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = debug$0.Config.createFrom;
const $$createType25 = $models.HardwareIdentityInfo.createFrom;
const $$createType26 = models$0.InventoryReport.createFrom;
const $$createType27 = supportmeta$0.KnowledgeArticle.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Array($$createType0);
const $$createType30 = $Create.Array($Create.Any);
const $$createType31 = mcp$0.Registry.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Array($$createType5);
const $$createType34 = $Create.Map($Create.Any, $Create.Any);
const $$createType35 = models$0.OsqueryStatus.createFrom;
const $$createType36 = p2pmeta$0.ArtifactAccess.createFrom;
const $$createType37 = p2pmeta$0.Config.createFrom;
const $$createType38 = p2pmeta$0.DebugStatus.createFrom;
const $$createType39 = p2pmeta$0.DistributionStatus.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = p2pmeta$0.PeerArtifactIndexView.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = p2pmeta$0.PeerView.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = p2pmeta$0.SeedPlanRecommendation.createFrom;
const $$createType46 = $models.PSADTDebugState.createFrom;
const $$createType47 = models$0.UpgradeItem.createFrom;
const $$createType48 = $Create.Array($$createType47);
const $$createType49 = debug$0.RealtimeStatus.createFrom;
const $$createType50 = $models.RuntimeFlags.createFrom;
const $$createType51 = $models.StatusOverview.createFrom;
const $$createType52 = $Create.Array($$createType3);
const $$createType53 = $Create.Array($$createType1);
const $$createType54 = supportmeta$0.APIWorkflowState.createFrom;
const $$createType55 = $Create.Array($$createType54);
const $$createType56 = $Create.Array($$createType10);
const $$createType57 = p2pmeta$0.AuditEvent.createFrom;
const $$createType58 = $Create.Array($$createType57);
const $$createType59 = models$0.ListeningPortInfo.createFrom;
const $$createType60 = $Create.Array($$createType59);
const $$createType61 = models$0.NetworkConnectionsReport.createFrom;
const $$createType62 = models$0.SoftwareItem.createFrom;
const $$createType63 = $Create.Array($$createType62);
const $$createType64 = models$0.StartupItem.createFrom;
const $$createType65 = $Create.Array($$createType64);
const $$createType66 = $models.PSADTPreflightResult.createFrom;
