// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * DB encapsula a conexão SQLite e operações de cache
 */
export class DB {
    /**
     * Creates a new DB instance.
     * @param {Partial<DB>} [$$source = {}] - The source object to create the DB.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DB instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DB}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DB(/** @type {Partial<DB>} */($$parsedSource));
    }
}

/**
 * MemoryNote representa uma anotação/memória local persistida.
 */
export class MemoryNote {
    /**
     * Creates a new MemoryNote instance.
     * @param {Partial<MemoryNote>} [$$source = {}] - The source object to create the MemoryNote.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryNote instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryNote}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryNote(/** @type {Partial<MemoryNote>} */($$parsedSource));
    }
}
