// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class AppItem {
    /**
     * Creates a new AppItem instance.
     * @param {Partial<AppItem>} [$$source = {}] - The source object to create the AppItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("publisher" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publisher"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("homepage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["homepage"] = "";
        }
        if (!("license" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["license"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("installCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installCommand"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastUpdated"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppItem}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new AppItem(/** @type {Partial<AppItem>} */($$parsedSource));
    }
}

export class AutoexecItem {
    /**
     * Creates a new AutoexecItem instance.
     * @param {Partial<AutoexecItem>} [$$source = {}] - The source object to create the AutoexecItem.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoexecItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutoexecItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutoexecItem(/** @type {Partial<AutoexecItem>} */($$parsedSource));
    }
}

export class BatteryInfo {
    /**
     * Creates a new BatteryInfo instance.
     * @param {Partial<BatteryInfo>} [$$source = {}] - The source object to create the BatteryInfo.
     */
    constructor($$source = {}) {
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("serialNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serialNumber"] = "";
        }
        if (!("cycleCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cycleCount"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("charging" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["charging"] = false;
        }
        if (!("charged" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["charged"] = false;
        }
        if (!("designedCapacityMAh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["designedCapacityMAh"] = 0;
        }
        if (!("maxCapacityMAh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxCapacityMAh"] = 0;
        }
        if (!("currentCapacityMAh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentCapacityMAh"] = 0;
        }
        if (!("percentRemaining" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percentRemaining"] = 0;
        }
        if (!("amperageMA" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["amperageMA"] = 0;
        }
        if (!("voltageMV" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["voltageMV"] = 0;
        }
        if (!("minutesUntilEmpty" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minutesUntilEmpty"] = 0;
        }
        if (!("minutesToFullCharge" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minutesToFullCharge"] = 0;
        }
        if (!("chemistry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chemistry"] = "";
        }
        if (!("health" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["health"] = "";
        }
        if (!("condition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["condition"] = "";
        }
        if (!("manufactureDateEpoch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["manufactureDateEpoch"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatteryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatteryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatteryInfo(/** @type {Partial<BatteryInfo>} */($$parsedSource));
    }
}

export class BitLockerInfo {
    /**
     * Creates a new BitLockerInfo instance.
     * @param {Partial<BitLockerInfo>} [$$source = {}] - The source object to create the BitLockerInfo.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("driveLetter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["driveLetter"] = "";
        }
        if (!("persistentVolumeId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["persistentVolumeId"] = "";
        }
        if (!("conversionStatus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conversionStatus"] = 0;
        }
        if (!("protectionStatus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["protectionStatus"] = 0;
        }
        if (!("encryptionMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["encryptionMethod"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("percentageEncrypted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percentageEncrypted"] = 0;
        }
        if (!("lockStatus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lockStatus"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BitLockerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BitLockerInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BitLockerInfo(/** @type {Partial<BitLockerInfo>} */($$parsedSource));
    }
}

export class CPUFeature {
    /**
     * Creates a new CPUFeature instance.
     * @param {Partial<CPUFeature>} [$$source = {}] - The source object to create the CPUFeature.
     */
    constructor($$source = {}) {
        if (!("feature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feature"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("outputRegister" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputRegister"] = "";
        }
        if (!("outputBit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputBit"] = 0;
        }
        if (!("inputEAX" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputEAX"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CPUFeature instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CPUFeature}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CPUFeature(/** @type {Partial<CPUFeature>} */($$parsedSource));
    }
}

export class CPUInfo {
    /**
     * Creates a new CPUInfo instance.
     * @param {Partial<CPUInfo>} [$$source = {}] - The source object to create the CPUInfo.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("processorType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["processorType"] = "";
        }
        if (!("cpuStatus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuStatus"] = 0;
        }
        if (!("numberOfCores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["numberOfCores"] = 0;
        }
        if (!("logicalProcessors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["logicalProcessors"] = 0;
        }
        if (!("addressWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["addressWidth"] = 0;
        }
        if (!("currentClockSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentClockSpeed"] = 0;
        }
        if (!("maxClockSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxClockSpeed"] = 0;
        }
        if (!("socketDesignation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["socketDesignation"] = "";
        }
        if (!("availability" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["availability"] = "";
        }
        if (!("loadPercentage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["loadPercentage"] = 0;
        }
        if (!("numberOfEfficiencyCores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["numberOfEfficiencyCores"] = 0;
        }
        if (!("numberOfPerformanceCores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["numberOfPerformanceCores"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CPUInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CPUInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CPUInfo(/** @type {Partial<CPUInfo>} */($$parsedSource));
    }
}

export class Catalog {
    /**
     * Creates a new Catalog instance.
     * @param {Partial<Catalog>} [$$source = {}] - The source object to create the Catalog.
     */
    constructor($$source = {}) {
        if (!("generated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generated"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("packagesWithIcon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["packagesWithIcon"] = 0;
        }
        if (!("packages" in $$source)) {
            /**
             * @member
             * @type {AppItem[]}
             */
            this["packages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Catalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Catalog}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("packages" in $$parsedSource) {
            $$parsedSource["packages"] = $$createField3_0($$parsedSource["packages"]);
        }
        return new Catalog(/** @type {Partial<Catalog>} */($$parsedSource));
    }
}

export class DiskInfo {
    /**
     * Creates a new DiskInfo instance.
     * @param {Partial<DiskInfo>} [$$source = {}] - The source object to create the DiskInfo.
     */
    constructor($$source = {}) {
        if (!("device" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("fileSystem" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileSystem"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("mediaType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mediaType"] = "";
        }
        if (!("sizeGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeGB"] = 0;
        }
        if (!("freeGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["freeGB"] = 0;
        }
        if (!("freeKnown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["freeKnown"] = false;
        }
        if (!("bootPartition" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bootPartition"] = false;
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("partitions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["partitions"] = 0;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskInfo(/** @type {Partial<DiskInfo>} */($$parsedSource));
    }
}

export class GPUInfo {
    /**
     * Creates a new GPUInfo instance.
     * @param {Partial<GPUInfo>} [$$source = {}] - The source object to create the GPUInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("driverVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["driverVersion"] = "";
        }
        if (!("vramGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vramGB"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GPUInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GPUInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GPUInfo(/** @type {Partial<GPUInfo>} */($$parsedSource));
    }
}

export class HardwareInfo {
    /**
     * Creates a new HardwareInfo instance.
     * @param {Partial<HardwareInfo>} [$$source = {}] - The source object to create the HardwareInfo.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("serialNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serialNumber"] = "";
        }
        if (!("cpu" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cpu"] = "";
        }
        if (!("logicalCores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["logicalCores"] = 0;
        }
        if (!("cores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cores"] = 0;
        }
        if (!("memoryGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memoryGB"] = 0;
        }
        if (!("motherboardManufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["motherboardManufacturer"] = "";
        }
        if (!("motherboardModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["motherboardModel"] = "";
        }
        if (!("motherboardSerial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["motherboardSerial"] = "";
        }
        if (!("biosVendor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["biosVendor"] = "";
        }
        if (!("biosVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["biosVersion"] = "";
        }
        if (!("biosReleaseDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["biosReleaseDate"] = "";
        }
        if (!("biosSerial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["biosSerial"] = "";
        }
        if (!("memoryModulesCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memoryModulesCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HardwareInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HardwareInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HardwareInfo(/** @type {Partial<HardwareInfo>} */($$parsedSource));
    }
}

export class InventoryReport {
    /**
     * Creates a new InventoryReport instance.
     * @param {Partial<InventoryReport>} [$$source = {}] - The source object to create the InventoryReport.
     */
    constructor($$source = {}) {
        if (!("collectedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collectedAt"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("hardware" in $$source)) {
            /**
             * @member
             * @type {HardwareInfo}
             */
            this["hardware"] = (new HardwareInfo());
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {OperatingSystem}
             */
            this["os"] = (new OperatingSystem());
        }
        if (!("loggedInUsers" in $$source)) {
            /**
             * @member
             * @type {LoggedInUser[]}
             */
            this["loggedInUsers"] = [];
        }
        if (!("battery" in $$source)) {
            /**
             * @member
             * @type {BatteryInfo[]}
             */
            this["battery"] = [];
        }
        if (!("bitLocker" in $$source)) {
            /**
             * @member
             * @type {BitLockerInfo[]}
             */
            this["bitLocker"] = [];
        }
        if (!("cpuInfo" in $$source)) {
            /**
             * @member
             * @type {CPUInfo[]}
             */
            this["cpuInfo"] = [];
        }
        if (!("cpuFeatures" in $$source)) {
            /**
             * @member
             * @type {CPUFeature[]}
             */
            this["cpuFeatures"] = [];
        }
        if (!("memoryModules" in $$source)) {
            /**
             * @member
             * @type {MemoryModule[]}
             */
            this["memoryModules"] = [];
        }
        if (!("monitors" in $$source)) {
            /**
             * @member
             * @type {MonitorInfo[]}
             */
            this["monitors"] = [];
        }
        if (!("gpus" in $$source)) {
            /**
             * @member
             * @type {GPUInfo[]}
             */
            this["gpus"] = [];
        }
        if (!("volumes" in $$source)) {
            /**
             * @member
             * @type {DiskInfo[]}
             */
            this["volumes"] = [];
        }
        if (!("physicalDisks" in $$source)) {
            /**
             * @member
             * @type {DiskInfo[]}
             */
            this["physicalDisks"] = [];
        }
        if (!("disks" in $$source)) {
            /**
             * @member
             * @type {DiskInfo[]}
             */
            this["disks"] = [];
        }
        if (!("networks" in $$source)) {
            /**
             * @member
             * @type {NetworkInfo[]}
             */
            this["networks"] = [];
        }
        if (!("listeningPorts" in $$source)) {
            /**
             * @member
             * @type {ListeningPortInfo[]}
             */
            this["listeningPorts"] = [];
        }
        if (!("openSockets" in $$source)) {
            /**
             * @member
             * @type {OpenSocketInfo[]}
             */
            this["openSockets"] = [];
        }
        if (!("printers" in $$source)) {
            /**
             * @member
             * @type {PrinterInfo[]}
             */
            this["printers"] = [];
        }
        if (!("software" in $$source)) {
            /**
             * @member
             * @type {SoftwareItem[]}
             */
            this["software"] = [];
        }
        if (!("startupItems" in $$source)) {
            /**
             * @member
             * @type {StartupItem[]}
             */
            this["startupItems"] = [];
        }
        if (!("autoexec" in $$source)) {
            /**
             * @member
             * @type {AutoexecItem[]}
             */
            this["autoexec"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InventoryReport}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType12;
        const $$createField8_0 = $$createType14;
        const $$createField9_0 = $$createType16;
        const $$createField10_0 = $$createType18;
        const $$createField11_0 = $$createType20;
        const $$createField12_0 = $$createType22;
        const $$createField13_0 = $$createType22;
        const $$createField14_0 = $$createType22;
        const $$createField15_0 = $$createType24;
        const $$createField16_0 = $$createType26;
        const $$createField17_0 = $$createType28;
        const $$createField18_0 = $$createType30;
        const $$createField19_0 = $$createType32;
        const $$createField20_0 = $$createType34;
        const $$createField21_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hardware" in $$parsedSource) {
            $$parsedSource["hardware"] = $$createField2_0($$parsedSource["hardware"]);
        }
        if ("os" in $$parsedSource) {
            $$parsedSource["os"] = $$createField3_0($$parsedSource["os"]);
        }
        if ("loggedInUsers" in $$parsedSource) {
            $$parsedSource["loggedInUsers"] = $$createField4_0($$parsedSource["loggedInUsers"]);
        }
        if ("battery" in $$parsedSource) {
            $$parsedSource["battery"] = $$createField5_0($$parsedSource["battery"]);
        }
        if ("bitLocker" in $$parsedSource) {
            $$parsedSource["bitLocker"] = $$createField6_0($$parsedSource["bitLocker"]);
        }
        if ("cpuInfo" in $$parsedSource) {
            $$parsedSource["cpuInfo"] = $$createField7_0($$parsedSource["cpuInfo"]);
        }
        if ("cpuFeatures" in $$parsedSource) {
            $$parsedSource["cpuFeatures"] = $$createField8_0($$parsedSource["cpuFeatures"]);
        }
        if ("memoryModules" in $$parsedSource) {
            $$parsedSource["memoryModules"] = $$createField9_0($$parsedSource["memoryModules"]);
        }
        if ("monitors" in $$parsedSource) {
            $$parsedSource["monitors"] = $$createField10_0($$parsedSource["monitors"]);
        }
        if ("gpus" in $$parsedSource) {
            $$parsedSource["gpus"] = $$createField11_0($$parsedSource["gpus"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField12_0($$parsedSource["volumes"]);
        }
        if ("physicalDisks" in $$parsedSource) {
            $$parsedSource["physicalDisks"] = $$createField13_0($$parsedSource["physicalDisks"]);
        }
        if ("disks" in $$parsedSource) {
            $$parsedSource["disks"] = $$createField14_0($$parsedSource["disks"]);
        }
        if ("networks" in $$parsedSource) {
            $$parsedSource["networks"] = $$createField15_0($$parsedSource["networks"]);
        }
        if ("listeningPorts" in $$parsedSource) {
            $$parsedSource["listeningPorts"] = $$createField16_0($$parsedSource["listeningPorts"]);
        }
        if ("openSockets" in $$parsedSource) {
            $$parsedSource["openSockets"] = $$createField17_0($$parsedSource["openSockets"]);
        }
        if ("printers" in $$parsedSource) {
            $$parsedSource["printers"] = $$createField18_0($$parsedSource["printers"]);
        }
        if ("software" in $$parsedSource) {
            $$parsedSource["software"] = $$createField19_0($$parsedSource["software"]);
        }
        if ("startupItems" in $$parsedSource) {
            $$parsedSource["startupItems"] = $$createField20_0($$parsedSource["startupItems"]);
        }
        if ("autoexec" in $$parsedSource) {
            $$parsedSource["autoexec"] = $$createField21_0($$parsedSource["autoexec"]);
        }
        return new InventoryReport(/** @type {Partial<InventoryReport>} */($$parsedSource));
    }
}

export class ListeningPortInfo {
    /**
     * Creates a new ListeningPortInfo instance.
     * @param {Partial<ListeningPortInfo>} [$$source = {}] - The source object to create the ListeningPortInfo.
     */
    constructor($$source = {}) {
        if (!("processName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["processName"] = "";
        }
        if (!("processId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["processId"] = 0;
        }
        if (!("processPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["processPath"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListeningPortInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListeningPortInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListeningPortInfo(/** @type {Partial<ListeningPortInfo>} */($$parsedSource));
    }
}

export class LoggedInUser {
    /**
     * Creates a new LoggedInUser instance.
     * @param {Partial<LoggedInUser>} [$$source = {}] - The source object to create the LoggedInUser.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("tty" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tty"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("sid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sid"] = "";
        }
        if (!("registry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["registry"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoggedInUser instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoggedInUser}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoggedInUser(/** @type {Partial<LoggedInUser>} */($$parsedSource));
    }
}

export class MemoryModule {
    /**
     * Creates a new MemoryModule instance.
     * @param {Partial<MemoryModule>} [$$source = {}] - The source object to create the MemoryModule.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["handle"] = "";
        }
        if (!("arrayHandle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arrayHandle"] = "";
        }
        if (!("formFactor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["formFactor"] = "";
        }
        if (!("totalWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalWidth"] = 0;
        }
        if (!("dataWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dataWidth"] = 0;
        }
        if (!("sizeMB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeMB"] = 0;
        }
        if (!("set" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["set"] = 0;
        }
        if (!("slot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slot"] = "";
        }
        if (!("bank" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bank"] = "";
        }
        if (!("memoryTypeDetails" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["memoryTypeDetails"] = "";
        }
        if (!("maxSpeedMTs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxSpeedMTs"] = 0;
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("partNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["partNumber"] = "";
        }
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("assetTag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetTag"] = "";
        }
        if (!("sizeGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeGB"] = 0;
        }
        if (!("speedMHz" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speedMHz"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("minVoltageMV" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minVoltageMV"] = 0;
        }
        if (!("maxVoltageMV" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxVoltageMV"] = 0;
        }
        if (!("configuredVoltageMV" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["configuredVoltageMV"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryModule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryModule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryModule(/** @type {Partial<MemoryModule>} */($$parsedSource));
    }
}

export class MonitorInfo {
    /**
     * Creates a new MonitorInfo instance.
     * @param {Partial<MonitorInfo>} [$$source = {}] - The source object to create the MonitorInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("resolution" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resolution"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MonitorInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorInfo(/** @type {Partial<MonitorInfo>} */($$parsedSource));
    }
}

export class NetworkConnectionsReport {
    /**
     * Creates a new NetworkConnectionsReport instance.
     * @param {Partial<NetworkConnectionsReport>} [$$source = {}] - The source object to create the NetworkConnectionsReport.
     */
    constructor($$source = {}) {
        if (!("collectedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collectedAt"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("listeningPorts" in $$source)) {
            /**
             * @member
             * @type {ListeningPortInfo[]}
             */
            this["listeningPorts"] = [];
        }
        if (!("openSockets" in $$source)) {
            /**
             * @member
             * @type {OpenSocketInfo[]}
             */
            this["openSockets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkConnectionsReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkConnectionsReport}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType26;
        const $$createField3_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("listeningPorts" in $$parsedSource) {
            $$parsedSource["listeningPorts"] = $$createField2_0($$parsedSource["listeningPorts"]);
        }
        if ("openSockets" in $$parsedSource) {
            $$parsedSource["openSockets"] = $$createField3_0($$parsedSource["openSockets"]);
        }
        return new NetworkConnectionsReport(/** @type {Partial<NetworkConnectionsReport>} */($$parsedSource));
    }
}

export class NetworkInfo {
    /**
     * Creates a new NetworkInfo instance.
     * @param {Partial<NetworkInfo>} [$$source = {}] - The source object to create the NetworkInfo.
     */
    constructor($$source = {}) {
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("friendlyName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["friendlyName"] = "";
        }
        if (!("mac" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mac"] = "";
        }
        if (!("ipv4" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ipv4"] = "";
        }
        if (!("ipv6" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ipv6"] = "";
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("mtu" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mtu"] = 0;
        }
        if (!("linkSpeedMbps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["linkSpeedMbps"] = 0;
        }
        if (!("connectionStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectionStatus"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("physicalAdapter" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["physicalAdapter"] = false;
        }
        if (!("dhcpEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dhcpEnabled"] = false;
        }
        if (!("dnsServers" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dnsServers"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInfo(/** @type {Partial<NetworkInfo>} */($$parsedSource));
    }
}

export class OpenSocketInfo {
    /**
     * Creates a new OpenSocketInfo instance.
     * @param {Partial<OpenSocketInfo>} [$$source = {}] - The source object to create the OpenSocketInfo.
     */
    constructor($$source = {}) {
        if (!("processName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["processName"] = "";
        }
        if (!("processId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["processId"] = 0;
        }
        if (!("processPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["processPath"] = "";
        }
        if (!("localAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAddress"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("remoteAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteAddress"] = "";
        }
        if (!("remotePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("family" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["family"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenSocketInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenSocketInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenSocketInfo(/** @type {Partial<OpenSocketInfo>} */($$parsedSource));
    }
}

export class OperatingSystem {
    /**
     * Creates a new OperatingSystem instance.
     * @param {Partial<OperatingSystem>} [$$source = {}] - The source object to create the OperatingSystem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("build" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["build"] = "";
        }
        if (!("architecture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["architecture"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperatingSystem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OperatingSystem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperatingSystem(/** @type {Partial<OperatingSystem>} */($$parsedSource));
    }
}

export class OsqueryStatus {
    /**
     * Creates a new OsqueryStatus instance.
     * @param {Partial<OsqueryStatus>} [$$source = {}] - The source object to create the OsqueryStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("suggestedPackageID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["suggestedPackageID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OsqueryStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OsqueryStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OsqueryStatus(/** @type {Partial<OsqueryStatus>} */($$parsedSource));
    }
}

export class PrinterInfo {
    /**
     * Creates a new PrinterInfo instance.
     * @param {Partial<PrinterInfo>} [$$source = {}] - The source object to create the PrinterInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("driverName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["driverName"] = "";
        }
        if (!("portName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["portName"] = "";
        }
        if (!("printerStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["printerStatus"] = "";
        }
        if (!("isDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }
        if (!("isNetworkPrinter" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isNetworkPrinter"] = false;
        }
        if (!("shared" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["shared"] = false;
        }
        if (!("shareName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shareName"] = "";
        }
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrinterInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrinterInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrinterInfo(/** @type {Partial<PrinterInfo>} */($$parsedSource));
    }
}

export class SoftwareItem {
    /**
     * Creates a new SoftwareItem instance.
     * @param {Partial<SoftwareItem>} [$$source = {}] - The source object to create the SoftwareItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("publisher" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publisher"] = "";
        }
        if (!("installId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installId"] = "";
        }
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("installDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installDate"] = "";
        }
        if (!("installSource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installSource"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SoftwareItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SoftwareItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SoftwareItem(/** @type {Partial<SoftwareItem>} */($$parsedSource));
    }
}

export class StartupItem {
    /**
     * Creates a new StartupItem instance.
     * @param {Partial<StartupItem>} [$$source = {}] - The source object to create the StartupItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["args"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartupItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupItem(/** @type {Partial<StartupItem>} */($$parsedSource));
    }
}

/**
 * UpgradeItem represents a single package with a pending update.
 */
export class UpgradeItem {
    /**
     * Creates a new UpgradeItem instance.
     * @param {Partial<UpgradeItem>} [$$source = {}] - The source object to create the UpgradeItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("availableVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["availableVersion"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpgradeItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpgradeItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpgradeItem(/** @type {Partial<UpgradeItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AppItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = HardwareInfo.createFrom;
const $$createType4 = OperatingSystem.createFrom;
const $$createType5 = LoggedInUser.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = BatteryInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = BitLockerInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = CPUInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = CPUFeature.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = MemoryModule.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = MonitorInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = GPUInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = DiskInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = NetworkInfo.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = ListeningPortInfo.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = OpenSocketInfo.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = PrinterInfo.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = SoftwareItem.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = StartupItem.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = AutoexecItem.createFrom;
const $$createType36 = $Create.Array($$createType35);
