// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    APITicket,
    APIWorkflowState,
    AgentInfo,
    CloseTicketInput,
    CreateTicketInput,
    KnowledgeArticle,
    TicketComment
} from "./models.js";

import * as $models from "./models.js";

/**
 * TicketPriority normalizes priority values from API responses.
 * @typedef {$models.TicketPriority} TicketPriority
 */
