// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * APITicket is the ticket representation returned by the remote API.
 */
export class APITicket {
    /**
     * Creates a new APITicket instance.
     * @param {Partial<APITicket>} [$$source = {}] - The source object to create the APITicket.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {TicketPriority}
             */
            this["priority"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["category"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["agentId"] = undefined;
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["siteId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DepartmentID é o departamento do chamado; a IA usa em get_department_fields.
             * @member
             * @type {string | null | undefined}
             */
            this["departmentId"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updatedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["closedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {APIWorkflowState | null | undefined}
             */
            this["workflowState"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * WorkflowStateID é o id do estado atual. A API do agent devolve a entidade
             * crua (sem o objeto workflowState), então a UI resolve nome/cor/isFinal pelo
             * endpoint me/tickets/workflow-states usando este id.
             * @member
             * @type {string | undefined}
             */
            this["workflowStateId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["rating"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["ratedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["ratedBy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * RatingFeedback é o comentário textual da avaliação (CSAT).
             * @member
             * @type {string | null | undefined}
             */
            this["ratingFeedback"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Template usado na abertura (nome preservado no histórico).
             * @member
             * @type {string | null | undefined}
             */
            this["templateId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["templateName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Snapshot markdown (somente leitura) do formulário/template enviado na abertura.
             * @member
             * @type {string | null | undefined}
             */
            this["submissionSnapshotMarkdown"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APITicket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APITicket}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workflowState" in $$parsedSource) {
            $$parsedSource["workflowState"] = $$createField12_0($$parsedSource["workflowState"]);
        }
        return new APITicket(/** @type {Partial<APITicket>} */($$parsedSource));
    }
}

/**
 * APIWorkflowState is the workflow state embedded in a ticket response.
 */
export class APIWorkflowState {
    /**
     * Creates a new APIWorkflowState instance.
     * @param {Partial<APIWorkflowState>} [$$source = {}] - The source object to create the APIWorkflowState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("isInitial" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isInitial"] = false;
        }
        if (!("isFinal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFinal"] = false;
        }
        if (!("displayOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["displayOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIWorkflowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIWorkflowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIWorkflowState(/** @type {Partial<APIWorkflowState>} */($$parsedSource));
    }
}

/**
 * AgentInfo holds key identifiers resolved from the server for the connected agent.
 */
export class AgentInfo {
    /**
     * Creates a new AgentInfo instance.
     * @param {Partial<AgentInfo>} [$$source = {}] - The source object to create the AgentInfo.
     */
    constructor($$source = {}) {
        if (!("agentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentId"] = "";
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (!("siteId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteId"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentInfo(/** @type {Partial<AgentInfo>} */($$parsedSource));
    }
}

/**
 * CloseTicketInput is the frontend-facing request to close a ticket.
 */
export class CloseTicketInput {
    /**
     * Creates a new CloseTicketInput instance.
     * @param {Partial<CloseTicketInput>} [$$source = {}] - The source object to create the CloseTicketInput.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["rating"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["comment"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workflowStateId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseTicketInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloseTicketInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseTicketInput(/** @type {Partial<CloseTicketInput>} */($$parsedSource));
    }
}

/**
 * CreateTicketInput is the frontend-facing request to create a ticket.
 */
export class CreateTicketInput {
    /**
     * Creates a new CreateTicketInput instance.
     * @param {Partial<CreateTicketInput>} [$$source = {}] - The source object to create the CreateTicketInput.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Opcionais: quando preenchidos, o chamado nasce departamento/perfil e o
             * servidor calcula o SLA. Sem eles, o perfil padrão do departamento não se aplica.
             * @member
             * @type {string | undefined}
             */
            this["departmentId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workflowProfileId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Template opcional + valores dos campos personalizados (definitionId→valor)
             * + respostas do mini questionário do template (key→valor).
             * @member
             * @type {string | undefined}
             */
            this["templateId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["customFieldValues"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["templateAnswers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTicketInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTicketInput}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("customFieldValues" in $$parsedSource) {
            $$parsedSource["customFieldValues"] = $$createField7_0($$parsedSource["customFieldValues"]);
        }
        if ("templateAnswers" in $$parsedSource) {
            $$parsedSource["templateAnswers"] = $$createField8_0($$parsedSource["templateAnswers"]);
        }
        return new CreateTicketInput(/** @type {Partial<CreateTicketInput>} */($$parsedSource));
    }
}

/**
 * KnowledgeArticle represents a knowledge base article for support guidance.
 */
export class KnowledgeArticle {
    /**
     * Creates a new KnowledgeArticle instance.
     * @param {Partial<KnowledgeArticle>} [$$source = {}] - The source object to create the KnowledgeArticle.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("difficulty" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["difficulty"] = "";
        }
        if (!("readTimeMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["readTimeMin"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * Estado de publicação e versão (AgentKnowledgeArticleDto).
             * Hoje o endpoint do agent só entrega Published, mas o campo permite à UI
             * distinguir conteúdo atualizado (v{n}) quando outros status forem expostos.
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("currentVersionNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentVersionNumber"] = 0;
        }
        if (!("parentId" in $$source)) {
            /**
             * Hierarquia de páginas (estilo Notion)
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("isPage" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPage"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeArticle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnowledgeArticle}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new KnowledgeArticle(/** @type {Partial<KnowledgeArticle>} */($$parsedSource));
    }
}

/**
 * KnowledgePage represents a sub-page inside a knowledge article (Notion-style).
 * Pages can be nested up to 3 levels via ParentPageID. Children holds the nested tree.
 */
export class KnowledgePage {
    /**
     * Creates a new KnowledgePage instance.
     * @param {Partial<KnowledgePage>} [$$source = {}] - The source object to create the KnowledgePage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("articleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["articleId"] = "";
        }
        if (!("parentPageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentPageId"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("childCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["childCount"] = 0;
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {KnowledgePage[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgePage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnowledgePage}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new KnowledgePage(/** @type {Partial<KnowledgePage>} */($$parsedSource));
    }
}

/**
 * TicketAnswer é uma resposta do mini questionário do template de um chamado
 * (detalhe do agent, somente leitura).
 */
export class TicketAnswer {
    /**
     * Creates a new TicketAnswer instance.
     * @param {Partial<TicketAnswer>} [$$source = {}] - The source object to create the TicketAnswer.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("questionKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["questionKey"] = "";
        }
        if (!("questionLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["questionLabel"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["valueText"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketAnswer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketAnswer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketAnswer(/** @type {Partial<TicketAnswer>} */($$parsedSource));
    }
}

/**
 * TicketComment is a comment on a ticket.
 */
export class TicketComment {
    /**
     * Creates a new TicketComment instance.
     * @param {Partial<TicketComment>} [$$source = {}] - The source object to create the TicketComment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("isInternal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isInternal"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketComment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketComment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketComment(/** @type {Partial<TicketComment>} */($$parsedSource));
    }
}

/**
 * TicketDepartmentField descreve um campo personalizado público de um
 * departamento (formulário de abertura). Vale para todo chamado do
 * departamento, com ou sem template.
 */
export class TicketDepartmentField {
    /**
     * Creates a new TicketDepartmentField instance.
     * @param {Partial<TicketDepartmentField>} [$$source = {}] - The source object to create the TicketDepartmentField.
     */
    constructor($$source = {}) {
        if (!("definitionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["definitionId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("dataType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("isRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRequired"] = false;
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["options"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["validationRegex"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["inputMask"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["minLength"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["maxLength"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["minValue"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["maxValue"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketDepartmentField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketDepartmentField}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new TicketDepartmentField(/** @type {Partial<TicketDepartmentField>} */($$parsedSource));
    }
}

/**
 * TicketFieldValue é um campo personalizado do departamento com o valor gravado
 * no chamado (detalhe do agent, somente leitura).
 */
export class TicketFieldValue {
    /**
     * Creates a new TicketFieldValue instance.
     * @param {Partial<TicketFieldValue>} [$$source = {}] - The source object to create the TicketFieldValue.
     */
    constructor($$source = {}) {
        if (!("definitionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["definitionId"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("isRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRequired"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["valueJson"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketFieldValue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketFieldValue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketFieldValue(/** @type {Partial<TicketFieldValue>} */($$parsedSource));
    }
}

/**
 * TicketFormField descreve um campo do formulário de abertura de chamado do
 * agent. O agent NÃO tem lista fixa de campos/opções: ele só mostra o que o
 * servidor devolver (chave, rótulo, tipo, obrigatoriedade, visibilidade, valor
 * padrão e opções).
 */
export class TicketFormField {
    /**
     * Creates a new TicketFormField instance.
     * @param {Partial<TicketFormField>} [$$source = {}] - The source object to create the TicketFormField.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("visible" in $$source)) {
            /**
             * Visible é ponteiro de propósito: campo novo do servidor que não mandar
             * "visible" (nil) continua visível. Com bool puro o zero value (false)
             * esconderia o campo silenciosamente.
             * @member
             * @type {boolean | null}
             */
            this["visible"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["defaultValue"] = undefined;
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {TicketFormFieldOption[]}
             */
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketFormField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketFormField}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new TicketFormField(/** @type {Partial<TicketFormField>} */($$parsedSource));
    }
}

/**
 * TicketFormFieldOption é uma opção de um campo de seleção do formulário de
 * abertura de chamado. O servidor é a fonte da verdade: o agent renderiza
 * exatamente as opções recebidas.
 */
export class TicketFormFieldOption {
    /**
     * Creates a new TicketFormFieldOption instance.
     * @param {Partial<TicketFormFieldOption>} [$$source = {}] - The source object to create the TicketFormFieldOption.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketFormFieldOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketFormFieldOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketFormFieldOption(/** @type {Partial<TicketFormFieldOption>} */($$parsedSource));
    }
}

/**
 * TicketFormSchema é o schema do formulário de abertura de chamado de um
 * departamento. As opções variam por departamento (modelos ativos e histórico
 * do próprio departamento), por isso o agent só busca o schema depois que o
 * departamento é escolhido.
 */
export class TicketFormSchema {
    /**
     * Creates a new TicketFormSchema instance.
     * @param {Partial<TicketFormSchema>} [$$source = {}] - The source object to create the TicketFormSchema.
     */
    constructor($$source = {}) {
        if (!("departmentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["departmentId"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {TicketFormField[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketFormSchema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketFormSchema}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        return new TicketFormSchema(/** @type {Partial<TicketFormSchema>} */($$parsedSource));
    }
}

/**
 * TicketOptionDepartment is a department option for the agent ticket form.
 */
export class TicketOptionDepartment {
    /**
     * Creates a new TicketOptionDepartment instance.
     * @param {Partial<TicketOptionDepartment>} [$$source = {}] - The source object to create the TicketOptionDepartment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketOptionDepartment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketOptionDepartment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketOptionDepartment(/** @type {Partial<TicketOptionDepartment>} */($$parsedSource));
    }
}

/**
 * TicketOptionProfile is a workflow profile option for the agent ticket form.
 */
export class TicketOptionProfile {
    /**
     * Creates a new TicketOptionProfile instance.
     * @param {Partial<TicketOptionProfile>} [$$source = {}] - The source object to create the TicketOptionProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("departmentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["departmentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketOptionProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketOptionProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketOptionProfile(/** @type {Partial<TicketOptionProfile>} */($$parsedSource));
    }
}

/**
 * TicketOptions carries the department/profile pickers for the agent ticket form.
 */
export class TicketOptions {
    /**
     * Creates a new TicketOptions instance.
     * @param {Partial<TicketOptions>} [$$source = {}] - The source object to create the TicketOptions.
     */
    constructor($$source = {}) {
        if (!("departments" in $$source)) {
            /**
             * @member
             * @type {TicketOptionDepartment[]}
             */
            this["departments"] = [];
        }
        if (!("workflowProfiles" in $$source)) {
            /**
             * @member
             * @type {TicketOptionProfile[]}
             */
            this["workflowProfiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketOptions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("departments" in $$parsedSource) {
            $$parsedSource["departments"] = $$createField0_0($$parsedSource["departments"]);
        }
        if ("workflowProfiles" in $$parsedSource) {
            $$parsedSource["workflowProfiles"] = $$createField1_0($$parsedSource["workflowProfiles"]);
        }
        return new TicketOptions(/** @type {Partial<TicketOptions>} */($$parsedSource));
    }
}

/**
 * TicketPriority normalizes priority values from API responses.
 * @typedef {number} TicketPriority
 */

/**
 * TicketTemplateField descreve um campo personalizado de um template de chamado.
 */
export class TicketTemplateField {
    /**
     * Creates a new TicketTemplateField instance.
     * @param {Partial<TicketTemplateField>} [$$source = {}] - The source object to create the TicketTemplateField.
     */
    constructor($$source = {}) {
        if (!("definitionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["definitionId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("isRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRequired"] = false;
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["options"] = [];
        }
        if (!("validationRegex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["validationRegex"] = "";
        }
        if (!("inputMask" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputMask"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketTemplateField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketTemplateField}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new TicketTemplateField(/** @type {Partial<TicketTemplateField>} */($$parsedSource));
    }
}

/**
 * TicketTemplateOption é um template de abertura de chamado disponível ao agente.
 */
export class TicketTemplateOption {
    /**
     * Creates a new TicketTemplateOption instance.
     * @param {Partial<TicketTemplateOption>} [$$source = {}] - The source object to create the TicketTemplateOption.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["priority"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("departmentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["departmentId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * CustomFieldDefaultsJSON é o JSON (texto) de defaults dos campos do
             * departamento (definitionId -> valor) para pré-preencher o formulário.
             * @member
             * @type {string | undefined}
             */
            this["customFieldDefaultsJson"] = undefined;
        }
        if (!("questions" in $$source)) {
            /**
             * @member
             * @type {TicketTemplateQuestion[]}
             */
            this["questions"] = [];
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {TicketTemplateField[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketTemplateOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketTemplateOption}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType15;
        const $$createField9_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField8_0($$parsedSource["questions"]);
        }
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField9_0($$parsedSource["fields"]);
        }
        return new TicketTemplateOption(/** @type {Partial<TicketTemplateOption>} */($$parsedSource));
    }
}

/**
 * TicketTemplateQuestion é uma pergunta do mini questionário de um template.
 */
export class TicketTemplateQuestion {
    /**
     * Creates a new TicketTemplateQuestion instance.
     * @param {Partial<TicketTemplateQuestion>} [$$source = {}] - The source object to create the TicketTemplateQuestion.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("isRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRequired"] = false;
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["options"] = [];
        }
        if (!("validationRegex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["validationRegex"] = "";
        }
        if (!("inputMask" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputMask"] = "";
        }
        if (!("helpText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["helpText"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Limites usados na validação do cliente (o servidor também valida).
             * @member
             * @type {number | null | undefined}
             */
            this["minLength"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["maxLength"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["minValue"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["maxValue"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketTemplateQuestion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketTemplateQuestion}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new TicketTemplateQuestion(/** @type {Partial<TicketTemplateQuestion>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = APIWorkflowState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = KnowledgePage.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = TicketFormFieldOption.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = TicketFormField.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = TicketOptionDepartment.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = TicketOptionProfile.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = TicketTemplateQuestion.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = TicketTemplateField.createFrom;
const $$createType17 = $Create.Array($$createType16);
