// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * APITicket is the ticket representation returned by the remote API.
 */
export class APITicket {
    /**
     * Creates a new APITicket instance.
     * @param {Partial<APITicket>} [$$source = {}] - The source object to create the APITicket.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {TicketPriority}
             */
            this["priority"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["category"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["agentId"] = undefined;
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["siteId"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updatedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["closedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {APIWorkflowState | null | undefined}
             */
            this["workflowState"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["rating"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["ratedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["ratedBy"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APITicket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APITicket}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workflowState" in $$parsedSource) {
            $$parsedSource["workflowState"] = $$createField11_0($$parsedSource["workflowState"]);
        }
        return new APITicket(/** @type {Partial<APITicket>} */($$parsedSource));
    }
}

/**
 * APIWorkflowState is the workflow state embedded in a ticket response.
 */
export class APIWorkflowState {
    /**
     * Creates a new APIWorkflowState instance.
     * @param {Partial<APIWorkflowState>} [$$source = {}] - The source object to create the APIWorkflowState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("isInitial" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isInitial"] = false;
        }
        if (!("isFinal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFinal"] = false;
        }
        if (!("displayOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["displayOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIWorkflowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIWorkflowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIWorkflowState(/** @type {Partial<APIWorkflowState>} */($$parsedSource));
    }
}

/**
 * AgentInfo holds key identifiers resolved from the server for the connected agent.
 */
export class AgentInfo {
    /**
     * Creates a new AgentInfo instance.
     * @param {Partial<AgentInfo>} [$$source = {}] - The source object to create the AgentInfo.
     */
    constructor($$source = {}) {
        if (!("agentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentId"] = "";
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (!("siteId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteId"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentInfo(/** @type {Partial<AgentInfo>} */($$parsedSource));
    }
}

/**
 * CloseTicketInput is the frontend-facing request to close a ticket.
 */
export class CloseTicketInput {
    /**
     * Creates a new CloseTicketInput instance.
     * @param {Partial<CloseTicketInput>} [$$source = {}] - The source object to create the CloseTicketInput.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["rating"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["comment"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workflowStateId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseTicketInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloseTicketInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseTicketInput(/** @type {Partial<CloseTicketInput>} */($$parsedSource));
    }
}

/**
 * CreateTicketInput is the frontend-facing request to create a ticket.
 */
export class CreateTicketInput {
    /**
     * Creates a new CreateTicketInput instance.
     * @param {Partial<CreateTicketInput>} [$$source = {}] - The source object to create the CreateTicketInput.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Opcionais: quando preenchidos, o chamado nasce departamento/perfil e o
             * servidor calcula o SLA. Sem eles, o perfil padrão do departamento não se aplica.
             * @member
             * @type {string | undefined}
             */
            this["departmentId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workflowProfileId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTicketInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTicketInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTicketInput(/** @type {Partial<CreateTicketInput>} */($$parsedSource));
    }
}

/**
 * KnowledgeArticle represents a knowledge base article for support guidance.
 */
export class KnowledgeArticle {
    /**
     * Creates a new KnowledgeArticle instance.
     * @param {Partial<KnowledgeArticle>} [$$source = {}] - The source object to create the KnowledgeArticle.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("difficulty" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["difficulty"] = "";
        }
        if (!("readTimeMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["readTimeMin"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * Estado de publicação e versão (AgentKnowledgeArticleDto).
             * Hoje o endpoint do agent só entrega Published, mas o campo permite à UI
             * distinguir conteúdo atualizado (v{n}) quando outros status forem expostos.
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("currentVersionNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentVersionNumber"] = 0;
        }
        if (!("parentId" in $$source)) {
            /**
             * Hierarquia de páginas (estilo Notion)
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("isPage" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPage"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeArticle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnowledgeArticle}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new KnowledgeArticle(/** @type {Partial<KnowledgeArticle>} */($$parsedSource));
    }
}

/**
 * KnowledgePage represents a sub-page inside a knowledge article (Notion-style).
 * Pages can be nested up to 3 levels via ParentPageID. Children holds the nested tree.
 */
export class KnowledgePage {
    /**
     * Creates a new KnowledgePage instance.
     * @param {Partial<KnowledgePage>} [$$source = {}] - The source object to create the KnowledgePage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("articleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["articleId"] = "";
        }
        if (!("parentPageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentPageId"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("childCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["childCount"] = 0;
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {KnowledgePage[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgePage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnowledgePage}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new KnowledgePage(/** @type {Partial<KnowledgePage>} */($$parsedSource));
    }
}

/**
 * TicketComment is a comment on a ticket.
 */
export class TicketComment {
    /**
     * Creates a new TicketComment instance.
     * @param {Partial<TicketComment>} [$$source = {}] - The source object to create the TicketComment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("isInternal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isInternal"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketComment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketComment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketComment(/** @type {Partial<TicketComment>} */($$parsedSource));
    }
}

/**
 * TicketOptionDepartment is a department option for the agent ticket form.
 */
export class TicketOptionDepartment {
    /**
     * Creates a new TicketOptionDepartment instance.
     * @param {Partial<TicketOptionDepartment>} [$$source = {}] - The source object to create the TicketOptionDepartment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketOptionDepartment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketOptionDepartment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketOptionDepartment(/** @type {Partial<TicketOptionDepartment>} */($$parsedSource));
    }
}

/**
 * TicketOptionProfile is a workflow profile option for the agent ticket form.
 */
export class TicketOptionProfile {
    /**
     * Creates a new TicketOptionProfile instance.
     * @param {Partial<TicketOptionProfile>} [$$source = {}] - The source object to create the TicketOptionProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("departmentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["departmentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketOptionProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketOptionProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketOptionProfile(/** @type {Partial<TicketOptionProfile>} */($$parsedSource));
    }
}

/**
 * TicketOptions carries the department/profile pickers for the agent ticket form.
 */
export class TicketOptions {
    /**
     * Creates a new TicketOptions instance.
     * @param {Partial<TicketOptions>} [$$source = {}] - The source object to create the TicketOptions.
     */
    constructor($$source = {}) {
        if (!("departments" in $$source)) {
            /**
             * @member
             * @type {TicketOptionDepartment[]}
             */
            this["departments"] = [];
        }
        if (!("workflowProfiles" in $$source)) {
            /**
             * @member
             * @type {TicketOptionProfile[]}
             */
            this["workflowProfiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketOptions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("departments" in $$parsedSource) {
            $$parsedSource["departments"] = $$createField0_0($$parsedSource["departments"]);
        }
        if ("workflowProfiles" in $$parsedSource) {
            $$parsedSource["workflowProfiles"] = $$createField1_0($$parsedSource["workflowProfiles"]);
        }
        return new TicketOptions(/** @type {Partial<TicketOptions>} */($$parsedSource));
    }
}

/**
 * TicketPriority normalizes priority values from API responses.
 * @typedef {number} TicketPriority
 */

// Private type creation functions
const $$createType0 = APIWorkflowState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = KnowledgePage.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = TicketOptionDepartment.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = TicketOptionProfile.createFrom;
const $$createType8 = $Create.Array($$createType7);
