// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';
import {json} from '../models';
import {mcp} from '../models';

export function ClearChatHistory():Promise<void>;

export function ClearLogs():Promise<void>;

export function CreateSupportTicket(arg1:app.SupportTicket):Promise<app.SupportTicket>;

export function ExportInventoryMarkdown():Promise<string>;

export function ExportInventoryPDF():Promise<string>;

export function ExportMarkdown():Promise<string>;

export function ExportPDF():Promise<string>;

export function GetAgentStatus():Promise<app.AgentStatus>;

export function GetAvailableTools():Promise<Array<Record<string, string>>>;

export function GetCatalog():Promise<models.Catalog>;

export function GetChatConfig():Promise<app.ChatConfig>;

export function GetChatHistory():Promise<Array<app.ChatMessage>>;

export function GetDebugConfig():Promise<app.DebugConfig>;

export function GetInventory():Promise<models.InventoryReport>;

export function GetInventoryJSON():Promise<json.RawMessage>;

export function GetKnowledgeBaseArticles():Promise<Array<app.KnowledgeArticle>>;

export function GetLogs():Promise<Array<string>>;

export function GetLogsText():Promise<string>;

export function GetMCPRegistry():Promise<mcp.Registry>;

export function GetOsqueryStatus():Promise<models.OsqueryStatus>;

export function GetOsqueryStatusJSON():Promise<json.RawMessage>;

export function GetPendingUpdates():Promise<Array<models.UpgradeItem>>;

export function GetPendingUpdatesJSON():Promise<json.RawMessage>;

export function GetPackageActionsJSON():Promise<json.RawMessage>;

export function GetRealtimeStatus():Promise<app.RealtimeStatus>;

export function GetStartupError():Promise<string>;

export function GetSupportTickets():Promise<Array<app.SupportTicket>>;

export function Install(arg1:string):Promise<string>;

export function InstallOsquery():Promise<string>;

export function InstallPackage(arg1:string):Promise<string>;

export function ListInstalled():Promise<string>;

export function RefreshInventory():Promise<models.InventoryReport>;

export function RequestAppClose():Promise<void>;

export function SearchCatalog(arg1:string):Promise<json.RawMessage>;

export function SearchKnowledgeBaseArticles(arg1:string):Promise<Array<app.KnowledgeArticle>>;

export function SendChatMessage(arg1:string):Promise<string>;

export function SetChatConfig(arg1:app.ChatConfig):Promise<void>;

export function SetDebugConfig(arg1:app.DebugConfig):Promise<void>;

export function SetExportRedaction(arg1:boolean):Promise<void>;

export function ShouldHideOnClose():Promise<boolean>;

export function StartChatStream(arg1:string):Promise<void>;

export function TestChatConfig(arg1:app.ChatConfig):Promise<string>;

export function TestDebugConnection(arg1:app.DebugConfig):Promise<string>;

export function Uninstall(arg1:string):Promise<string>;

export function UninstallPackage(arg1:string):Promise<string>;

export function Upgrade(arg1:string):Promise<string>;

export function UpgradeAll():Promise<string>;

export function UpgradeAllPackages():Promise<string>;

export function UpgradePackage(arg1:string):Promise<string>;
