// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * DistributionStatusQueryOptions define filtros opcionais usados por
 * GET /api/v1/agent-auth/me/p2p/distribution-status.
 */
export class DistributionStatusQueryOptions {
    /**
     * Creates a new DistributionStatusQueryOptions instance.
     * @param {Partial<DistributionStatusQueryOptions>} [$$source = {}] - The source object to create the DistributionStatusQueryOptions.
     */
    constructor($$source = {}) {
        if (!("ArtifactID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ArtifactID"] = "";
        }
        if (!("Limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Limit"] = 0;
        }
        if (!("Offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DistributionStatusQueryOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DistributionStatusQueryOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DistributionStatusQueryOptions(/** @type {Partial<DistributionStatusQueryOptions>} */($$parsedSource));
    }
}
