// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChatHistory() {
  return window['go']['app']['App']['ClearChatHistory']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function CreateSupportTicket(arg1) {
  return window['go']['app']['App']['CreateSupportTicket'](arg1);
}

export function ExportInventoryMarkdown() {
  return window['go']['app']['App']['ExportInventoryMarkdown']();
}

export function ExportInventoryPDF() {
  return window['go']['app']['App']['ExportInventoryPDF']();
}

export function ExportMarkdown() {
  return window['go']['app']['App']['ExportMarkdown']();
}

export function ExportPDF() {
  return window['go']['app']['App']['ExportPDF']();
}

export function GetAgentStatus() {
  return window['go']['app']['App']['GetAgentStatus']();
}

export function GetAvailableTools() {
  return window['go']['app']['App']['GetAvailableTools']();
}

export function GetCatalog() {
  return window['go']['app']['App']['GetCatalog']();
}

export function GetChatConfig() {
  return window['go']['app']['App']['GetChatConfig']();
}

export function GetChatHistory() {
  return window['go']['app']['App']['GetChatHistory']();
}

export function GetDebugConfig() {
  return window['go']['app']['App']['GetDebugConfig']();
}

export function GetAgentConfiguration() {
  return window['go']['app']['App']['GetAgentConfiguration']();
}

export function GetInventory() {
  return window['go']['app']['App']['GetInventory']();
}

export function GetInventoryJSON() {
  return window['go']['app']['App']['GetInventoryJSON']();
}

export function GetKnowledgeBaseArticles() {
  return window['go']['app']['App']['GetKnowledgeBaseArticles']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetLogsText() {
  return window['go']['app']['App']['GetLogsText']();
}

export function GetMCPRegistry() {
  return window['go']['app']['App']['GetMCPRegistry']();
}

export function GetOsqueryStatus() {
  return window['go']['app']['App']['GetOsqueryStatus']();
}

export function GetOsqueryStatusJSON() {
  return window['go']['app']['App']['GetOsqueryStatusJSON']();
}

export function GetPendingUpdates() {
  return window['go']['app']['App']['GetPendingUpdates']();
}

export function GetPendingUpdatesJSON() {
  return window['go']['app']['App']['GetPendingUpdatesJSON']();
}

export function GetPackageActionsJSON() {
  return window['go']['app']['App']['GetPackageActionsJSON']();
}

export function GetRealtimeStatus() {
  return window['go']['app']['App']['GetRealtimeStatus']();
}

export function GetStartupError() {
  return window['go']['app']['App']['GetStartupError']();
}

export function GetSupportTickets() {
  return window['go']['app']['App']['GetSupportTickets']();
}

export function Install(arg1) {
  return window['go']['app']['App']['Install'](arg1);
}

export function InstallOsquery() {
  return window['go']['app']['App']['InstallOsquery']();
}

export function InstallPackage(arg1) {
  return window['go']['app']['App']['InstallPackage'](arg1);
}

export function ListInstalled() {
  return window['go']['app']['App']['ListInstalled']();
}

export function RefreshInventory() {
  return window['go']['app']['App']['RefreshInventory']();
}

export function RequestAppClose() {
  return window['go']['app']['App']['RequestAppClose']();
}

export function SearchCatalog(arg1) {
  return window['go']['app']['App']['SearchCatalog'](arg1);
}

export function SearchKnowledgeBaseArticles(arg1) {
  return window['go']['app']['App']['SearchKnowledgeBaseArticles'](arg1);
}

export function SendChatMessage(arg1) {
  return window['go']['app']['App']['SendChatMessage'](arg1);
}

export function SetChatConfig(arg1) {
  return window['go']['app']['App']['SetChatConfig'](arg1);
}

export function SetDebugConfig(arg1) {
  return window['go']['app']['App']['SetDebugConfig'](arg1);
}

export function SetExportRedaction(arg1) {
  return window['go']['app']['App']['SetExportRedaction'](arg1);
}

export function ShouldHideOnClose() {
  return window['go']['app']['App']['ShouldHideOnClose']();
}

export function StartChatStream(arg1) {
  return window['go']['app']['App']['StartChatStream'](arg1);
}

export function TestChatConfig(arg1) {
  return window['go']['app']['App']['TestChatConfig'](arg1);
}

export function TestDebugConnection(arg1) {
  return window['go']['app']['App']['TestDebugConnection'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['app']['App']['Uninstall'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['app']['App']['UninstallPackage'](arg1);
}

export function Upgrade(arg1) {
  return window['go']['app']['App']['Upgrade'](arg1);
}

export function UpgradeAll() {
  return window['go']['app']['App']['UpgradeAll']();
}

export function UpgradeAllPackages() {
  return window['go']['app']['App']['UpgradeAllPackages']();
}

export function UpgradePackage(arg1) {
  return window['go']['app']['App']['UpgradePackage'](arg1);
}
