// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * DispatchRequest é o payload de uma notificação.
 */
export class DispatchRequest {
    /**
     * Creates a new DispatchRequest instance.
     * @param {Partial<DispatchRequest>} [$$source = {}] - The source object to create the DispatchRequest.
     */
    constructor($$source = {}) {
        if (!("notificationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notificationId"] = "";
        }
        if (!("idempotencyKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["idempotencyKey"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("eventType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventType"] = "";
        }
        if (!("layout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["layout"] = "";
        }
        if (!("timeoutSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeoutSeconds"] = 0;
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DispatchRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DispatchRequest}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField9_0($$parsedSource["metadata"]);
        }
        return new DispatchRequest(/** @type {Partial<DispatchRequest>} */($$parsedSource));
    }
}

/**
 * DispatchResponse é a resposta de uma notificação.
 */
export class DispatchResponse {
    /**
     * Creates a new DispatchResponse instance.
     * @param {Partial<DispatchResponse>} [$$source = {}] - The source object to create the DispatchResponse.
     */
    constructor($$source = {}) {
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (!("notificationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notificationId"] = "";
        }
        if (!("agentAction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentAction"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DispatchResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DispatchResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DispatchResponse(/** @type {Partial<DispatchResponse>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
