// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Policy {
    /**
     * Creates a new Policy instance.
     * @param {Partial<Policy>} [$$source = {}] - The source object to create the Policy.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("checkOnStartup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["checkOnStartup"] = false;
        }
        if (!("checkPeriodically" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["checkPeriodically"] = false;
        }
        if (!("checkOnSyncManifest" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["checkOnSyncManifest"] = false;
        }
        if (!("checkEveryHours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["checkEveryHours"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["preferredArtifactType"] = undefined;
        }
        if (!("requireSignatureValidation" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requireSignatureValidation"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Policy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Policy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Policy(/** @type {Partial<Policy>} */($$parsedSource));
    }
}
