// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * ApiVersionInfo contém informações da versão e capacidades da API.
 */
export class ApiVersionInfo {
    /**
     * Creates a new ApiVersionInfo instance.
     * @param {Partial<ApiVersionInfo>} [$$source = {}] - The source object to create the ApiVersionInfo.
     */
    constructor($$source = {}) {
        if (!("Detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Detected"] = false;
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Features" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Features"] = [];
        }
        if (!("BaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["BaseURL"] = "";
        }
        if (!("CheckedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CheckedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiVersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApiVersionInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Features" in $$parsedSource) {
            $$parsedSource["Features"] = $$createField2_0($$parsedSource["Features"]);
        }
        return new ApiVersionInfo(/** @type {Partial<ApiVersionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
