// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class ArtifactAccess {
    /**
     * Creates a new ArtifactAccess instance.
     * @param {Partial<ArtifactAccess>} [$$source = {}] - The source object to create the ArtifactAccess.
     */
    constructor($$source = {}) {
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (!("artifactName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactName"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("checksumSha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksumSha256"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("expiresAtUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expiresAtUtc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactAccess instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactAccess}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtifactAccess(/** @type {Partial<ArtifactAccess>} */($$parsedSource));
    }
}

export class ArtifactAvailabilityView {
    /**
     * Creates a new ArtifactAvailabilityView instance.
     * @param {Partial<ArtifactAvailabilityView>} [$$source = {}] - The source object to create the ArtifactAvailabilityView.
     */
    constructor($$source = {}) {
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (!("artifactName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactName"] = "";
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (!("peerAgentIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["peerAgentIds"] = [];
        }
        if (!("peerCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["peerCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactAvailabilityView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactAvailabilityView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("peerAgentIds" in $$parsedSource) {
            $$parsedSource["peerAgentIds"] = $$createField3_0($$parsedSource["peerAgentIds"]);
        }
        return new ArtifactAvailabilityView(/** @type {Partial<ArtifactAvailabilityView>} */($$parsedSource));
    }
}

export class ArtifactView {
    /**
     * Creates a new ArtifactView instance.
     * @param {Partial<ArtifactView>} [$$source = {}] - The source object to create the ArtifactView.
     */
    constructor($$source = {}) {
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (!("artifactName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("modifiedAtUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modifiedAtUtc"] = "";
        }
        if (!("checksumSha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksumSha256"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("lastHeartbeatUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastHeartbeatUtc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtifactView(/** @type {Partial<ArtifactView>} */($$parsedSource));
    }
}

export class AuditEvent {
    /**
     * Creates a new AuditEvent instance.
     * @param {Partial<AuditEvent>} [$$source = {}] - The source object to create the AuditEvent.
     */
    constructor($$source = {}) {
        if (!("timestampUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestampUtc"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["artifactName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["peerAgentId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuditEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditEvent(/** @type {Partial<AuditEvent>} */($$parsedSource));
    }
}

/**
 * AutoProvisioningStats agrega contadores e eventos de auditoria do lado do
 * agente que realizou provisionamentos (peer configurado que entregou ofertas).
 */
export class AutoProvisioningStats {
    /**
     * Creates a new AutoProvisioningStats instance.
     * @param {Partial<AutoProvisioningStats>} [$$source = {}] - The source object to create the AutoProvisioningStats.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("totalProvisioned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalProvisioned"] = 0;
        }
        if (!("recentEvents" in $$source)) {
            /**
             * @member
             * @type {OnboardingAuditEvent[]}
             */
            this["recentEvents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoProvisioningStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutoProvisioningStats}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentEvents" in $$parsedSource) {
            $$parsedSource["recentEvents"] = $$createField2_0($$parsedSource["recentEvents"]);
        }
        return new AutoProvisioningStats(/** @type {Partial<AutoProvisioningStats>} */($$parsedSource));
    }
}

export class BootstrapConfig {
    /**
     * Creates a new BootstrapConfig instance.
     * @param {Partial<BootstrapConfig>} [$$source = {}] - The source object to create the BootstrapConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["bootstrapPeers"] = undefined;
        }
        if (!("preferLan" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["preferLan"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["cloudBootstrapEnabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BootstrapConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bootstrapPeers" in $$parsedSource) {
            $$parsedSource["bootstrapPeers"] = $$createField0_0($$parsedSource["bootstrapPeers"]);
        }
        return new BootstrapConfig(/** @type {Partial<BootstrapConfig>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("discoveryMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["discoveryMode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["p2pMode"] = undefined;
        }
        if (!("tempTtlHours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tempTtlHours"] = 0;
        }
        if (!("seedPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seedPercent"] = 0;
        }
        if (!("minSeeds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minSeeds"] = 0;
        }
        if (!("httpListenPortRangeStart" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpListenPortRangeStart"] = 0;
        }
        if (!("httpListenPortRangeEnd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpListenPortRangeEnd"] = 0;
        }
        if (!("authTokenRotationMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["authTokenRotationMinutes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sharedSecret"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["chunkSizeBytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["maxBandwidthBytesPerSec"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BootstrapConfig | undefined}
             */
            this["bootstrapConfig"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bootstrapConfig" in $$parsedSource) {
            $$parsedSource["bootstrapConfig"] = $$createField12_0($$parsedSource["bootstrapConfig"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class DebugStatus {
    /**
     * Creates a new DebugStatus instance.
     * @param {Partial<DebugStatus>} [$$source = {}] - The source object to create the DebugStatus.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("discoveryMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["discoveryMode"] = "";
        }
        if (!("knownPeers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["knownPeers"] = 0;
        }
        if (!("listenAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["listenAddress"] = "";
        }
        if (!("tempDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tempDir"] = "";
        }
        if (!("tempTtlHours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tempTtlHours"] = 0;
        }
        if (!("lastCleanupUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastCleanupUtc"] = "";
        }
        if (!("lastDiscoveryTickUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastDiscoveryTickUtc"] = "";
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("currentSeedPlan" in $$source)) {
            /**
             * @member
             * @type {SeedPlan}
             */
            this["currentSeedPlan"] = (new SeedPlan());
        }
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {Metrics}
             */
            this["metrics"] = (new Metrics());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DebugStatus}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType4;
        const $$createField10_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("currentSeedPlan" in $$parsedSource) {
            $$parsedSource["currentSeedPlan"] = $$createField9_0($$parsedSource["currentSeedPlan"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField10_0($$parsedSource["metrics"]);
        }
        return new DebugStatus(/** @type {Partial<DebugStatus>} */($$parsedSource));
    }
}

export class DistributionStatus {
    /**
     * Creates a new DistributionStatus instance.
     * @param {Partial<DistributionStatus>} [$$source = {}] - The source object to create the DistributionStatus.
     */
    constructor($$source = {}) {
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["artifactName"] = undefined;
        }
        if (!("peerCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["peerCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["peerAgentIds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastUpdatedUtc"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DistributionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DistributionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("peerAgentIds" in $$parsedSource) {
            $$parsedSource["peerAgentIds"] = $$createField3_0($$parsedSource["peerAgentIds"]);
        }
        return new DistributionStatus(/** @type {Partial<DistributionStatus>} */($$parsedSource));
    }
}

export class Metrics {
    /**
     * Creates a new Metrics instance.
     * @param {Partial<Metrics>} [$$source = {}] - The source object to create the Metrics.
     */
    constructor($$source = {}) {
        if (!("publishedArtifacts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["publishedArtifacts"] = 0;
        }
        if (!("replicationsStarted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["replicationsStarted"] = 0;
        }
        if (!("replicationsSucceeded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["replicationsSucceeded"] = 0;
        }
        if (!("replicationsFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["replicationsFailed"] = 0;
        }
        if (!("bytesServed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesServed"] = 0;
        }
        if (!("bytesDownloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesDownloaded"] = 0;
        }
        if (!("queuedReplications" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queuedReplications"] = 0;
        }
        if (!("activeReplications" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeReplications"] = 0;
        }
        if (!("autoDistributionRuns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["autoDistributionRuns"] = 0;
        }
        if (!("catalogRefreshRuns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["catalogRefreshRuns"] = 0;
        }
        if (!("chunkedDownloads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkedDownloads"] = 0;
        }
        if (!("chunksDownloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunksDownloaded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Metrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Metrics(/** @type {Partial<Metrics>} */($$parsedSource));
    }
}

export class OnboardingAuditEvent {
    /**
     * Creates a new OnboardingAuditEvent instance.
     * @param {Partial<OnboardingAuditEvent>} [$$source = {}] - The source object to create the OnboardingAuditEvent.
     */
    constructor($$source = {}) {
        if (!("timestampUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestampUtc"] = "";
        }
        if (!("sourceAgentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceAgentId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetAgentId"] = undefined;
        }
        if (!("serverUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverUrl"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnboardingAuditEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OnboardingAuditEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OnboardingAuditEvent(/** @type {Partial<OnboardingAuditEvent>} */($$parsedSource));
    }
}

export class PeerArtifactIndexView {
    /**
     * Creates a new PeerArtifactIndexView instance.
     * @param {Partial<PeerArtifactIndexView>} [$$source = {}] - The source object to create the PeerArtifactIndexView.
     */
    constructor($$source = {}) {
        if (!("peerAgentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peerAgentId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["peerHost"] = undefined;
        }
        if (!("lastUpdatedUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastUpdatedUtc"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {ArtifactView[]}
             */
            this["artifacts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerArtifactIndexView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PeerArtifactIndexView}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField4_0($$parsedSource["artifacts"]);
        }
        return new PeerArtifactIndexView(/** @type {Partial<PeerArtifactIndexView>} */($$parsedSource));
    }
}

export class PeerView {
    /**
     * Creates a new PeerView instance.
     * @param {Partial<PeerView>} [$$source = {}] - The source object to create the PeerView.
     */
    constructor($$source = {}) {
        if (!("agentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientId"] = undefined;
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("lastSeenUtc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSeenUtc"] = "";
        }
        if (!("knownPeers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["knownPeers"] = 0;
        }
        if (!("connectedVia" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectedVia"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PeerView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeerView(/** @type {Partial<PeerView>} */($$parsedSource));
    }
}

export class SeedPlan {
    /**
     * Creates a new SeedPlan instance.
     * @param {Partial<SeedPlan>} [$$source = {}] - The source object to create the SeedPlan.
     */
    constructor($$source = {}) {
        if (!("totalAgents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalAgents"] = 0;
        }
        if (!("configuredPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["configuredPercent"] = 0;
        }
        if (!("minSeeds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minSeeds"] = 0;
        }
        if (!("selectedSeeds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["selectedSeeds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeedPlan instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SeedPlan}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SeedPlan(/** @type {Partial<SeedPlan>} */($$parsedSource));
    }
}

export class SeedPlanRecommendation {
    /**
     * Creates a new SeedPlanRecommendation instance.
     * @param {Partial<SeedPlanRecommendation>} [$$source = {}] - The source object to create the SeedPlanRecommendation.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["siteId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["generatedAtUtc"] = undefined;
        }
        if (!("plan" in $$source)) {
            /**
             * @member
             * @type {SeedPlan}
             */
            this["plan"] = (new SeedPlan());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeedPlanRecommendation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SeedPlanRecommendation}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField2_0($$parsedSource["plan"]);
        }
        return new SeedPlanRecommendation(/** @type {Partial<SeedPlanRecommendation>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = OnboardingAuditEvent.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = BootstrapConfig.createFrom;
const $$createType4 = SeedPlan.createFrom;
const $$createType5 = Metrics.createFrom;
const $$createType6 = ArtifactView.createFrom;
const $$createType7 = $Create.Array($$createType6);
