// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ExportInventoryMarkdown() {
  return window['go']['main']['App']['ExportInventoryMarkdown']();
}

export function ExportInventoryPDF() {
  return window['go']['main']['App']['ExportInventoryPDF']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOsqueryStatus() {
  return window['go']['main']['App']['GetOsqueryStatus']();
}

export function GetPendingUpdates() {
  return window['go']['main']['App']['GetPendingUpdates']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function InstallOsquery() {
  return window['go']['main']['App']['InstallOsquery']();
}

export function ListInstalled() {
  return window['go']['main']['App']['ListInstalled']();
}

export function RefreshInventory() {
  return window['go']['main']['App']['RefreshInventory']();
}

export function SetExportRedaction(arg1) {
  return window['go']['main']['App']['SetExportRedaction'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function Upgrade(arg1) {
  return window['go']['main']['App']['Upgrade'](arg1);
}

export function UpgradeAll() {
  return window['go']['main']['App']['UpgradeAll']();
}
