// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearLogs():Promise<void>;

export function ExportInventoryMarkdown():Promise<string>;

export function ExportInventoryPDF():Promise<string>;

export function GetCatalog():Promise<models.Catalog>;

export function GetInventory():Promise<models.InventoryReport>;

export function GetLogs():Promise<Array<string>>;

export function GetOsqueryStatus():Promise<models.OsqueryStatus>;

export function GetPendingUpdates():Promise<Array<models.UpgradeItem>>;

export function GetStartupError():Promise<string>;

export function Install(arg1:string):Promise<string>;

export function InstallOsquery():Promise<string>;

export function ListInstalled():Promise<string>;

export function RefreshInventory():Promise<models.InventoryReport>;

export function SetExportRedaction(arg1:boolean):Promise<void>;

export function Uninstall(arg1:string):Promise<string>;

export function Upgrade(arg1:string):Promise<string>;

export function UpgradeAll():Promise<string>;
